In [1]:
import pandas as pd
import numpy as np
import json
import math
import sqlite3
import datetime
import html_to_json
import re
year = 2026
pd.set_option('display.max_columns', None)
cnx = sqlite3.connect('results.db')

def diff(df, column, suffixes):
    c1 = column + suffixes[0]
    c2 = column + suffixes[1]
    return df[df[c1].notnull() & df[c2].notnull() & (df[c1] != df[c2])]

# Toruń

```
curl 'https://live.sts-timing.pl/TrylogiaTorunskichLegend/I/api.php?action=load-more-results&i=0&d=2&p=false&filtr=false' >> torun.json 
echo >> torun.json 
curl 'https://live.sts-timing.pl/TrylogiaTorunskichLegend/I/api.php?action=load-more-results&i=500&d=2&p=false&filtr=false' >> torun.json 
echo >> torun.json 
```

In [2]:
html = '<table>'
with open('torun.json') as f:
    for line in f.readlines():
        html += json.loads(line)['html']

html += '</table>'
table = html_to_json.convert_tables(html)[0]
torun = pd.DataFrame(table, columns=[
    'place',
    'bib',
    'name',
    'city',
    'team',
    'gender',
    '_c0',
    'category',
    '_c1',
    'gun_time',
    'result_torun',
    '_c2',
])
torun = torun[['name', 'city', 'team', 'gender', 'category', 'result_torun']]
torun['name'] = torun['name'].str.upper()
torun['city'] = torun['city'].str.upper()
torun['category'] = torun['category'].str.slice(0, 3)
torun['team'] = torun['team'].str.upper().replace('', None)

fixes = [
    ('name', 'KUDLA AGNIESZKA', 'KUDŁA AGNIESZKA'),
    ('team', 'ECIT NORIAN / PARKRUN TORUŃ', 'PARKRUN TORUŃ'),
    ('name', 'SZARWIŃSKI SZARWIŃSKI', 'SZARWIŃSKI MARIUSZ'),
    ('team', 'AKTYWNY  GRUDZIĄDZ', 'AKTYWNY GRUDZIĄDZ'),
    ('team', 'BIEGOWI PRZYJACIELE.', 'BIEGOWI PRZYJACIELE'),
    ('team', 'T.G.SOKÓŁ GNIEWKOWO', 'T.G. SOKÓŁ GNIEWKOWO'),
    ('team', 'TG SOKÓŁ GNIEWKOWO', 'T.G. SOKÓŁ GNIEWKOWO'),
    ('team', 'GWIAZDY NESTLÉ FITNESS', 'GWIAZDY NESTLE FITNESS'),
    ('team', 'SOKÓŁ GNIEWKOWO', 'T.G. SOKÓŁ GNIEWKOWO'),
    ('name', 'JABLONSKI JAROSLAW', 'JABŁOŃSKI JAROSŁAW'),
    ('name', 'LOPATA SZYMON', 'ŁOPATA SZYMON'),
    ('name', 'CZAJKOWSKI ALEKSANDRA', 'CZAJKOWSKA ALEKSANDRA'),
    ('name', 'ZIELIŃSKI MACIEJ ZIELIŃSKI', 'ZIELIŃSKI MACIEJ'),
    ('name', 'PIASECKI KRZYSZOF', 'PIASECKI KRZYSZTOF'),
    ('name', 'TOMASZEWSKI MILOSZ', 'TOMASZEWSKI MIŁOSZ'),
    ('team', 'GKS FABIANKI RUN TORUŃ', 'GKS FABIANKI'),
    ('name', 'KRIGER ANNA', 'KRIGER-PRZYBYLSKA ANNA'),
    ('name', 'KRUSZYNA ROBER', 'KRUSZYNA ROBERT'),
    ('name', 'SOSNWOSKL WOJCIECH', 'SOSNOWSKI WOJCIECH'),
]
for field, from_, to_ in fixes:
    torun.loc[torun[field] == from_, field] = to_
    
torun

,name,city,team,gender,category,result_torun
0,RYNKOWSKI BARTOSZ,IŁAWA,None,M,M30,00:31:39
1,TOMASZEWSKI MACIEJ,TORUŃ,GKS FABIANKI,M,M30,00:32:41
2,RATAJCZYK PRZEMYSŁAW,ALEKSANDRÓW KUJAWSKI,TKKF KOLEJARZ BYDGOSZCZ,M,M30,00:33:15
3,SANKO ALIAKSANDR,GRUDZIĄDZ,None,M,M30,00:33:33
4,PIASECKI KRZYSZTOF,WŁOCŁAWEK,KUNA TEAM WŁOCŁAWEK,M,M30,00:33:54
...,...,...,...,...,...,...
504,OLSZOWY NIKODEM,TORUŃ,None,M,M20,01:13:49
505,ŁAPIŃSKI SZYMON,TORUŃ,KLEJONT NOLU,M,M40,01:15:11
506,LIWIŃSKI SŁAWOMIR,SĘKOCIN-LAS,None,M,M50,01:16:55
507,KUŁAKOWSKI ROBERT,TORUŃ,HENDRICKSON POLAND,M,M50,01:17:31
508,ADAMCZYK ZBIGNIEW,ZAMEK BIERZGŁOWSKI,ZABIEGANI ŁUBIANKA,M,M70,01:18:02

# Grudziądz

In [3]:
# curl https://wyniki.domtel-sport.pl/zawody/5-bronek-run-forest-edition/ | grep ptc_vars > grudziadz.js
with open('grudziadz.js') as f:
    raw_data = json.loads(f.read()[15:-2])['init_data']

data = [
    [
        r['Zawodnik'],
        r['Team'],
        r['Płeć'],
        r['Kat'],
        r['Czas netto'],
        r['Rocz']
    ]
    for r in raw_data
    if r['DYSTANS'] == '10:59-10 km' and r['Msc']
]
grudziadz = pd.DataFrame(data, columns=['name', 'team', 'gender', 'category', 'result_grudziadz', 'year_of_birth'])
grudziadz['name'] = grudziadz['name'].str.upper()
grudziadz['team'] = grudziadz['team'].str.upper().replace('', None)

fixes = [
    ('name', 'KOSCINSKI DAWID', 'KOŚCIŃSKI DAWID'),
]
for field, from_, to_ in fixes:
    grudziadz.loc[grudziadz[field] == from_, field] = to_

grudziadz

,name,team,gender,category,result_grudziadz,year_of_birth
0,DIDOVODIUK DMYTRO,None,M,M30,00:31:53,1987
1,WAŚKIEWICZ SEBASTIAN,KB BIEGAJĄCY DIETETYK TEAM,M,M30,00:34:05,1987
2,TOMASZEWSKI MACIEJ,GKS FABIANKI,M,M30,00:35:01,1988
3,JANKOWIAK DAREK,SAMISWOI,M,M30,00:35:36,1995
4,PETROW DANIEL,GRUDZIĄDZ,M,M40,00:36:41,1986
...,...,...,...,...,...,...
151,GRZESZAK DANUTA,None,K,K70,01:11:32,1953
152,LEWANDOWSKI WOJCIECH,None,M,M70,01:14:37,1952
153,BRAC-WALCZYK MAŁGORZATA,None,K,K65,01:16:56,1958
154,BŁASZCZAK STANISŁAW,WKB MARATOŃCZYK WŁOCŁAWEK,M,M80,01:19:28,1946
155,GERKA KRZYSZTOF,RKS LECH RYPIN,M,M65,01:22:03,1957

In [4]:
after_2 = torun.merge(grudziadz, on=['name', 'gender'], how='outer', suffixes=('_torun', '_grudziadz'))

In [5]:
diff(after_2, 'category', ('_torun', '_grudziadz')) # looks OK!

,name,city,team_torun,gender,category_torun,result_torun,team_grudziadz,category_grudziadz,result_grudziadz,year_of_birth
72,CZAJKOWSKA ALEKSANDRA,BYDGOSZCZ,None,K,K20,01:02:04,None,K16,00:59:37,1997
83,DANIELEWICZ DARIA,GNIEWKOWO,T.G. SOKÓŁ GNIEWKOWO,K,K20,00:48:31,T.G. SOKÓŁ GNIEWKOWO,K16,00:47:53,1998
110,DŁONIAK EDMUND,GNIEWKOWO,T.G. SOKÓŁ GNIEWKOWO,M,M70,01:06:27,T.G. SOKÓŁ GNIEWKOWO,M80,01:06:05,1945
124,GABIZDALSKA ALICJA,OSTROWO,T.G. SOKÓŁ GNIEWKOWO,K,K20,00:57:36,T.G. SOKÓŁ GNIEWKOWO,K16,00:58:10,1999
354,MĄCZKA ZBIGNIEW,TORUŃ,PARKRUN TORUŃ,M,M60,00:48:11,PARKRUN TORUŃ,M65,00:47:38,1957
407,PIONTEK ELŻBIETA,BYDGOSZCZ,None,K,K60,01:01:58,None,K65,01:06:59,1957
464,SOWIŃSKI EDMUND,PŁOCK,TKKF PŁOCK,M,M70,01:03:06,TKKF PŁOCK,M80,01:04:06,1942
604,ŻYŁKOWSKA KRYSTYNA,TORUN,PARKRUN TORUŃ,K,K60,00:51:36,PARKRUN TORUŃ,K65,00:54:53,1960

In [6]:
diff(after_2, 'team', ('_torun', '_grudziadz')) # looks OK!

,name,city,team_torun,gender,category_torun,result_torun,team_grudziadz,category_grudziadz,result_grudziadz,year_of_birth
570,WĄŻ SŁAWOMIR,GRĘBOCIN,GWIAZDY NESTLE FITNESS,M,M50,01:03:50,RCR,M50,01:01:34,1972
593,ŁOPATA SZYMON,PAPOWO TORUNSKIE,BIEGOWI PRZYJACIELE,M,M40,00:41:04,PAPOWO TORUŃSKIE,M40,00:42:57,1986

In [7]:
after_2['team'] = after_2['team_grudziadz'].combine_first(after_2['team_torun'])
after_2['category'] = after_2['category_grudziadz'].combine_first(after_2['category_torun'])
after_2 = after_2.drop(labels=['team_grudziadz', 'team_torun', 'category_grudziadz', 'category_torun'], axis=1)
after_2

,name,city,gender,result_torun,result_grudziadz,year_of_birth,team,category
0,ADAMCZYK ZBIGNIEW,ZAMEK BIERZGŁOWSKI,M,01:18:02,NaN,NaN,ZABIEGANI ŁUBIANKA,M70
1,AFTYKA TOMASZ,GRUDZIĄDZ,M,00:50:03,NaN,NaN,RTR,M50
2,AGUADO OREGUI LIDIA,TORUŃ,K,00:49:55,NaN,NaN,None,K20
3,ANDRZEJCZAK MACIEJ,ŁĘCZYCA,M,00:42:21,NaN,NaN,ZESPÓŁ SZKÓŁ IM. JADWIGI GRODZKIEJ,M16
4,ANTONOWICZ WOJCIECH,SZCZECIN,M,00:45:07,NaN,NaN,None,M60
...,...,...,...,...,...,...,...,...
601,ŻUCHOWSKA PAULINA,NaN,K,NaN,00:49:49,1996,AZS UMK TORUŃ,K30
602,ŻUCHOWSKI RADOSŁAW,TORUŃ,M,00:55:10,NaN,NaN,None,M30
603,ŻYŁA JUSTYNA,NaN,K,NaN,00:50:27,1977,LA RIVE SPORT TEAM,K40
604,ŻYŁKOWSKA KRYSTYNA,TORUN,K,00:51:36,00:54:53,1960,PARKRUN TORUŃ,K65
605,ŻÓRAWSKA BARBARA,WARSZAWA,K,01:03:45,NaN,NaN,None,K20

# Fabianki

In [8]:
# curl https://wyniki.domtel-sport.pl/zawody/fabianki-na-dyche/ | grep ptc_vars > fabianki.js
with open('fabianki.js') as f:
    raw_data = json.loads(f.read()[15:-2])['init_data']

data = [
    [
        r['Zawodnik'],
        r['Team'],
        r['Płeć'],
        r['Kat'],
        r['Czas netto'],
        r['Rocz']
    ]
    for r in raw_data
    if r['Msc'] and r['Zawodnik'] not in ('WOJCIECHOWSKI Sławomir')
]
fabianki = pd.DataFrame(data, columns=['name', 'team', 'gender', 'category', 'result_fabianki', 'year_of_birth'])
fabianki['name'] = fabianki['name'].str.upper()
fabianki['team'] = fabianki['team'].str.upper().replace('', None)

fixes = [
    ('team', 'PARKUN TORUŃ', 'PARKRUN TORUŃ'),
    ('team', 'KUNA TEAM', 'KUNA TEAM WŁOCŁAWEK'),
    ('name', 'ROGOZINSKI DAWID', 'ROGOZIŃSKI DAWID'),
    ('team', 'TTKF PŁOCK', 'TKKF PŁOCK'),
]
for field, from_, to_ in fixes:
    fabianki.loc[fabianki[field] == from_, field] = to_

fabianki

,name,team,gender,category,result_fabianki,year_of_birth
0,TOMASZEWSKI MACIEJ,GKS FABIANKI,M,M30,00:33:04,1988
1,RATAJCZYK PRZEMYSŁAW,TKKF KOLEJARZ BYDGOSZCZ,M,M30,00:33:40,1993
2,JARANOWSKI ANDRZEJ,GKS FABIANKI,M,M30,00:33:57,1993
3,ROGOZIŃSKI DAWID,TEAMOCHAL,M,M30,00:34:44,1988
4,PIASECKI KRZYSZTOF,KUNA TEAM WŁOCŁAWEK,M,M30,00:34:52,1988
...,...,...,...,...,...,...
164,WLAZLO-WNUKIEWICZ ANNA,KROJCZYN,K,K40,01:13:28,1983
165,GLAZIK RENATA,FABIANKI,K,K50,01:13:31,1975
166,GERKA KRZYSZTOF,RKS LECH RYPIN,M,M60,01:14:02,1957
167,BŁASZCZAK STANISŁAW,WKB MARATOŃCZYK WŁOCŁAWEK,M,M80+,01:14:40,1946
168,MĄCZKA MAŁGORZATA,PARKRUN TORUŃ,K,K60,01:17:39,1961

In [9]:
after_3 = after_2.merge(fabianki, on=['name', 'gender'], how='outer', suffixes=('_base', '_fabianki'))

In [10]:
diff(after_3, 'category', ('_base', '_fabianki')) # looks OK!

,name,city,gender,result_torun,result_grudziadz,year_of_birth_base,team_base,category_base,team_fabianki,category_fabianki,result_fabianki,year_of_birth_fabianki
20,BEREBECKI ROMAN,NaN,M,NaN,00:50:29,1951,RKS LECH RYPIN,M75,RKS LECH RYPIN,M70,00:49:01,1951
54,BŁASZCZAK STANISŁAW,NaN,M,NaN,01:19:28,1946,WKB MARATOŃCZYK WŁOCŁAWEK,M80,WKB MARATOŃCZYK WŁOCŁAWEK,M80+,01:14:40,1946
124,DŁONIAK EDMUND,GNIEWKOWO,M,01:06:27,01:06:05,1945,T.G. SOKÓŁ GNIEWKOWO,M80,T.G. SOKÓŁ GNIEWKOWO,M80+,01:03:58,1945
146,GERKA KRZYSZTOF,NaN,M,NaN,01:22:03,1957,RKS LECH RYPIN,M65,RKS LECH RYPIN,M60,01:14:02,1957
176,GRZESZAK DANUTA,MOGILNO,K,01:07:28,01:11:32,1953,None,K70,MOGILNO,K70+,01:06:21,1953
354,MACIEJA BARTOSZ,SZPETAL GÓRNY,M,00:39:25,NaN,NaN,KUNA TEAM WŁOCŁAWEK,M20,KUNA TEAM WŁOCŁAWEK,M16,00:38:29,2006
394,MĄCZKA ZBIGNIEW,TORUŃ,M,00:48:11,00:47:38,1957,PARKRUN TORUŃ,M65,PARKRUN TORUŃ,M60,00:46:59,1957
421,OSTROWSKI SZYMON,WŁOCŁAWEK,M,00:41:26,NaN,NaN,None,M20,WŁOCŁAWEK,M16,00:41:07,1997
448,PIETRZAK MICHAŁ,WŁOCŁAWK,M,00:35:51,NaN,NaN,KUNA TEAM WŁOCŁAWEK,M20,KUNA TEAM WŁOCŁAWEK,M16,00:36:42,2005
454,PIOTROWICZ IRENEUSZ,NaN,M,NaN,00:55:41,1960,NaN,M65,PIOTRKÓW KUJAWSKI,M60,00:52:08,1960
563,SŁUNIECKA ALEKSANDRA,TORUŃ,K,00:49:41,NaN,NaN,PARKRUN TORUŃ,K20,PARKRUN TORUŃ,K16,00:51:07,2002
617,WIŚNIEWSKI DAMIAN,,M,00:43:44,NaN,NaN,None,,KUJAWSKO-POMORSKIE,M30,00:42:54,1987
620,WIŚNIEWSKI KAROL,TORUŃ,M,00:58:00,NaN,NaN,None,M20,PŁOCK,M16,00:54:52,1998
678,ŻYŁKOWSKA KRYSTYNA,TORUN,K,00:51:36,00:54:53,1960,PARKRUN TORUŃ,K65,PARKRUN TORUŃ,K60,00:51:38,1960

In [11]:
diff(after_3, 'year_of_birth', ('_base', '_fabianki')) # looks OK!

Empty DataFrame
Columns: [name, city, gender, result_torun, result_grudziadz, year_of_birth_base, team_base, category_base, team_fabianki, category_fabianki, result_fabianki, year_of_birth_fabianki]
Index: []

In [12]:
diff(after_3, 'team', ('_base', '_fabianki')) # looks OK!

,name,city,gender,result_torun,result_grudziadz,year_of_birth_base,team_base,category_base,team_fabianki,category_fabianki,result_fabianki,year_of_birth_fabianki
305,KUBERSKI KRZYSZTOF,LIPNO,M,00:44:29,NaN,NaN,ARCZ*CIACH,M30,ARCZCIACH,M30,00:41:22,1989
637,WĄŻ SŁAWOMIR,GRĘBOCIN,M,01:03:50,01:01:34,1972,RCR,M50,GRĘBOCIN,M50,00:54:22,1972

In [13]:
after_3['team'] = after_3['team_base'].combine_first(after_3['team_fabianki'])
after_3['category'] = after_3['category_base'].combine_first(after_3['category_fabianki'])
after_3['year_of_birth'] = after_3['year_of_birth_base'].combine_first(after_3['year_of_birth_fabianki'])
after_3 = after_3.drop(labels=['team_base', 'team_fabianki', 'category_base', 'category_fabianki', 'year_of_birth_base', 'year_of_birth_fabianki'], axis=1)
after_3

,name,city,gender,result_torun,result_grudziadz,result_fabianki,team,category,year_of_birth
0,ADAMCZYK ZBIGNIEW,ZAMEK BIERZGŁOWSKI,M,01:18:02,NaN,NaN,ZABIEGANI ŁUBIANKA,M70,NaN
1,AFTYKA TOMASZ,GRUDZIĄDZ,M,00:50:03,NaN,NaN,RTR,M50,NaN
2,AGUADO OREGUI LIDIA,TORUŃ,K,00:49:55,NaN,NaN,NaN,K20,NaN
3,ANDRZEJCZAK MACIEJ,ŁĘCZYCA,M,00:42:21,NaN,NaN,ZESPÓŁ SZKÓŁ IM. JADWIGI GRODZKIEJ,M16,NaN
4,ANTONOWICZ WOJCIECH,SZCZECIN,M,00:45:07,NaN,NaN,NaN,M60,NaN
...,...,...,...,...,...,...,...,...,...
675,ŻUCHOWSKI JÓZEF,NaN,M,NaN,NaN,00:40:32,PŁONNE,M50,1971
676,ŻUCHOWSKI RADOSŁAW,TORUŃ,M,00:55:10,NaN,NaN,NaN,M30,NaN
677,ŻYŁA JUSTYNA,NaN,K,NaN,00:50:27,NaN,LA RIVE SPORT TEAM,K40,1977
678,ŻYŁKOWSKA KRYSTYNA,TORUN,K,00:51:36,00:54:53,00:51:38,PARKRUN TORUŃ,K65,1960
679,ŻÓRAWSKA BARBARA,WARSZAWA,K,01:03:45,NaN,NaN,NaN,K20,NaN

## Waganiec

```
curl 'https://live.sts-timing.pl/waganiec2026/api.php?action=load-more-results&i=0&d=1&p=false&filtr=false' >> waganiec.json
echo >> waganiec.json 
curl 'https://live.sts-timing.pl/waganiec2026/api.php?action=load-more-results&i=100&d=1&p=false&filtr=false' >> waganiec.json
echo >> waganiec.json 
```

In [14]:
html = '<table>'
with open('waganiec.json') as f:
    for line in f.readlines():
        html += json.loads(line)['html']

html += '</table>'
table = html_to_json.convert_tables(html)[0]
waganiec = pd.DataFrame(table, columns=[
    'place',
    'bib',
    'name',
    'country',
    'city',
    'team',
    'gender',
    '_c0',
    'category',
    '_c1',
    'gun_time',
    'result_waganiec',
    '_c2',
])
waganiec = waganiec[['name', 'city', 'team', 'gender', 'result_waganiec', 'category']]
waganiec['name'] = waganiec['name'].str.upper()
waganiec['city'] = waganiec['city'].str.upper()
waganiec['team'] = waganiec['team'].str.upper().replace('', None)
waganiec['result_waganiec'] = waganiec['result_waganiec'].str.zfill(8).replace('^000', '00:', regex=True)
waganiec['category'] = waganiec['category'] + '0'

fixes = [
    ('team', 'TG SOKÓŁ GNIEWKOWO', 'T.G. SOKÓŁ GNIEWKOWO'),
    ('team', 'PARKRUN TORUN', 'PARKRUN TORUŃ'),
    ('team', 'PARKTUN TORUŃ', 'PARKRUN TORUŃ'),
    ('team', 'PARKUN TORUŃ', 'PARKRUN TORUŃ'),
    ('team', 'PARKRUN  TORUŃ', 'PARKRUN TORUŃ'),
    ('team', 'PARKRUN NOWY PARK SOLANKOWY, INOWROCŁAW', 'PARKRUN NOWY PARK SOLANKOWY INOWROCŁAW'),
    ('team', 'KUNA TEAM WLOCLAWEK', 'KUNA TEAM WŁOCŁAWEK'),
    ('team', 'WATAHA ŁĄCZY NAS BIEGANIE', 'WATAHA - ŁĄCZY NAS BIEGANIE'),
    ('name', 'KRIGER PRZYBYLSKA ANNA', 'KRIGER-PRZYBYLSKA ANNA'),
    ('team', 'WKB MARATOŃYK WŁOCŁAWEK', 'WKB MARATOŃCZYK WŁOCŁAWEK'),
]
for field, from_, to_ in fixes:
    waganiec.loc[waganiec[field] == from_, field] = to_

waganiec.loc[(waganiec['name'] == 'LEWANDOWSKI MACIEJ') & (waganiec['city'] == 'KONECK'), 'name'] = 'LEWANDOWSKI MACIEJ (KONECK)'
    
waganiec

,name,city,team,gender,result_waganiec,category
0,TOMASZEWSKI MACIEJ,TORUŃ,GKS FABIANKI,M,00:33:00,M30
1,RATAJCZYK PRZEMYSŁAW,ALEKSANDRÓW KUJAWSKI,TKKF KOLEJARZ BYDGOSZCZ,M,00:33:35,M30
2,TOMASZEWSKI MIŁOSZ,TORUŃ,GKS FABIANKI,M,00:33:38,M30
3,JARANOWSKI ANDRZEJ,BRODNICA,GKS FABIANKI,M,00:34:13,M30
4,JANKOWIAK DAREK,STRZELNO,SAMISWOI,M,00:34:49,M30
...,...,...,...,...,...,...
160,BOBER JOANNA,ALEKSANDRÓW KUJAWSKI,None,K,01:16:22,K30
161,BŁASZCZAK STANISŁAW,SKĘPE,WKB MARATOŃCZYK WŁOCŁAWEK,M,01:16:22,M70
162,ROSZAK MARZENA,GNIEWKOWO,None,K,01:25:23,K30
163,GERKA KRZYSZTOF,BRZUZE,RKS LECH RYPIN,M,01:26:41,M60
164,DOBROWOLSKI STANISŁAW,WAGANIEC,None,M,01:28:12,M70

In [15]:
after_4 = after_3.merge(waganiec, on=['name', 'gender'], how='outer', suffixes=('_base', '_waganiec'))

In [16]:
diff(after_4, 'team', ('_base', '_waganiec')) # looks OK!

Empty DataFrame
Columns: [name, city_base, gender, result_torun, result_grudziadz, result_fabianki, team_base, category_base, year_of_birth, city_waganiec, team_waganiec, result_waganiec, category_waganiec]
Index: []

In [17]:
diff(after_4, 'category', ('_base', '_waganiec')) # looks OK!

,name,city_base,gender,result_torun,result_grudziadz,result_fabianki,team_base,category_base,year_of_birth,city_waganiec,team_waganiec,result_waganiec,category_waganiec
21,BEREBECKI ROMAN,NaN,M,NaN,00:50:29,00:49:01,RKS LECH RYPIN,M75,1951,RYPIN,RKS LECH RYPIN,00:49:09,M70
58,BŁASZCZAK STANISŁAW,NaN,M,NaN,01:19:28,01:14:40,WKB MARATOŃCZYK WŁOCŁAWEK,M80,1946,SKĘPE,WKB MARATOŃCZYK WŁOCŁAWEK,01:16:22,M70
85,CZAJKOWSKA ALEKSANDRA,BYDGOSZCZ,K,01:02:04,00:59:37,00:55:35,BYDGOSZCZ,K16,1997,BYDGOSZCZ,None,00:58:55,K20
128,DZIEŁAK PATRYCJA,CZYSTOCHLEB,K,01:02:05,NaN,00:52:56,CZYSTOCHLEB,K16,2008,CZYSTOCHLEB,None,00:58:55,K10
133,DŁONIAK EDMUND,GNIEWKOWO,M,01:06:27,01:06:05,01:03:58,T.G. SOKÓŁ GNIEWKOWO,M80,1945,GNIEWKOWO,T.G. SOKÓŁ GNIEWKOWO,01:04:38,M70
141,FRĄCKOWIAK PAWEŁ,JANIKOWO,M,00:53:38,NaN,NaN,NaN,M16,NaN,JANIKOWO,None,00:55:45,M10
156,GERKA KRZYSZTOF,NaN,M,NaN,01:22:03,01:14:02,RKS LECH RYPIN,M65,1957,BRZUZE,RKS LECH RYPIN,01:26:41,M60
273,KIPRIJANOVSKI WIKTORIA,NaN,K,NaN,NaN,00:39:13,KUJAWSKO-POMORSKIE,K16,2001,TORUN,KUJAWSKO-POMORSKIE,00:38:51,K20
278,KLIMEK WIKTOR,NaN,M,NaN,NaN,00:47:26,KRUKOWO,M16,2007,CHOCEŃ,None,00:46:51,M10
423,MĄCZKA ZBIGNIEW,TORUŃ,M,00:48:11,00:47:38,00:46:59,PARKRUN TORUŃ,M65,1957,TORUŃ,PARKRUN TORUŃ,00:49:26,M60
479,PIEROWSKI ARKADIUSZ,NaN,M,NaN,NaN,00:53:57,ŁĘG WITOSZYN,M16,1997,ŁĘG WITOSZYN,None,00:53:05,M20
486,PIOTROWICZ IRENEUSZ,NaN,M,NaN,00:55:41,00:52:08,PIOTRKÓW KUJAWSKI,M65,1960,PIOTRKÓW KUJAWSKI,None,00:53:35,M60
563,SOWIŃSKI EDMUND,PŁOCK,M,01:03:06,01:04:06,NaN,TKKF PŁOCK,M80,1942,PŁOCK,TKKF PŁOCK,01:03:28,M70
667,WIŚNIEWSKI DAMIAN,,M,00:43:44,NaN,00:42:54,KUJAWSKO-POMORSKIE,,1987,TORUŃ,KUJAWSKO-POMORSKIE,00:44:02,M30

In [18]:
diff(after_4, 'city', ('_base', '_waganiec')) # looks OK!

,name,city_base,gender,result_torun,result_grudziadz,result_fabianki,team_base,category_base,year_of_birth,city_waganiec,team_waganiec,result_waganiec,category_waganiec
71,CHĘSIAK MATEUSZ,WAGANIEC,M,00:46:53,NaN,NaN,NaN,M30,NaN,WŁOSZYCA,None,00:47:25,M30
92,CZERENKIEWICZ-PAŁUCKA JOANNA,WŁOCŁAWEK,K,00:47:31,00:49:23,00:46:53,KUNA TEAM WŁOCŁAWEK,K50,1975,MACHNACZ,KUNA TEAM WŁOCŁAWEK,00:48:07,K50
149,GAC MONIKA,TORUŃ,K,00:49:23,00:51:39,00:48:31,T.G. SOKÓŁ GNIEWKOWO,K50,1976,GNIEWKOWO,T.G. SOKÓŁ GNIEWKOWO,00:49:11,K50
359,LEWANDOWSKI ARTUR,WŁOCŁAWEK,M,00:50:48,NaN,00:47:07,KUNA TEAM WŁOCŁAWEK,M50,1971,SZPETAL GÓRNY,KUNA TEAM WŁOCŁAWEK,00:47:22,M50
482,PIKULSKA JOANNA,LITYCHOWO,K,00:57:04,00:52:10,00:49:56,KS ZRYW RADZIEJÓW,K30,1988,BYTOŃ,KS ZRYW RADZIEJÓW,00:52:19,K30
534,RZĄD SZYMON,TORUŃ,M,00:38:30,NaN,NaN,GRIT RC TORUŃ,M20,NaN,TORUN,None,00:39:15,M20
667,WIŚNIEWSKI DAMIAN,,M,00:43:44,NaN,00:42:54,KUJAWSKO-POMORSKIE,,1987,TORUŃ,KUJAWSKO-POMORSKIE,00:44:02,M30
675,WOJCIECHOWSKI SŁAWOMIR,LUBICZ DOLNY,M,00:58:33,NaN,NaN,PARKRUN TORUŃ,M40,NaN,TORUŃ,PARKRUN TORUŃ,00:59:03,M40

In [19]:
after_4['team'] = after_4['team_base'].combine_first(after_4['team_waganiec'])
after_4['category'] = after_4['category_base'].combine_first(after_4['category_waganiec'])
after_4['city'] = after_4['city_base'].combine_first(after_4['city_waganiec'])
after_4 = after_4.drop(labels=['team_base', 'team_waganiec', 'category_waganiec', 'category_base', 'city_base', 'city_waganiec'], axis=1)
after_4

,name,gender,result_torun,result_grudziadz,result_fabianki,year_of_birth,result_waganiec,team,category,city
0,ADAMCZYK ZBIGNIEW,M,01:18:02,NaN,NaN,NaN,NaN,ZABIEGANI ŁUBIANKA,M70,ZAMEK BIERZGŁOWSKI
1,AFTYKA TOMASZ,M,00:50:03,NaN,NaN,NaN,NaN,RTR,M50,GRUDZIĄDZ
2,AGUADO OREGUI LIDIA,K,00:49:55,NaN,NaN,NaN,NaN,NaN,K20,TORUŃ
3,ANDRZEJCZAK MACIEJ,M,00:42:21,NaN,NaN,NaN,NaN,ZESPÓŁ SZKÓŁ IM. JADWIGI GRODZKIEJ,M16,ŁĘCZYCA
4,ANTONOWICZ WOJCIECH,M,00:45:07,NaN,NaN,NaN,NaN,NaN,M60,SZCZECIN
...,...,...,...,...,...,...,...,...,...,...
729,ŻUCHOWSKI JÓZEF,M,NaN,NaN,00:40:32,1971,00:41:43,PŁONNE,M50,RADOMIN
730,ŻUCHOWSKI RADOSŁAW,M,00:55:10,NaN,NaN,NaN,NaN,NaN,M30,TORUŃ
731,ŻYŁA JUSTYNA,K,NaN,00:50:27,NaN,1977,NaN,LA RIVE SPORT TEAM,K40,NaN
732,ŻYŁKOWSKA KRYSTYNA,K,00:51:36,00:54:53,00:51:38,1960,NaN,PARKRUN TORUŃ,K65,TORUN
733,ŻÓRAWSKA BARBARA,K,01:03:45,NaN,NaN,NaN,NaN,NaN,K20,WARSZAWA

# Brześć Kujawski

In [20]:
# $ curl 'https://my2.raceresult.com/399387/results/list?key=5a95b83bbf569fdc5c596f26d1cf3f73&listname=WYNIKI%7C01-WYNIKI%20KLASYFIKACJI%20GENERALNEJ&page=results&contest=0&r=group&name=%231_10%20km&f=%0C%3CIgnore%3E%0C%3CIgnore%3E' > brzesc.json

results = []
with open('brzesc.json') as f:
    data = json.load(f)
    for row in data['data']:
        # for idx, f in enumerate(row):
        #     print(idx, f)
        # xxx
        if len(row) != 27:
            continue
        team, city = re.match('(.*) \\((.*)\\)', row[5].upper()).groups()
        results.append([
            row[4].upper(),
            city,
            row[8],
            team or None,
            row[12][:3],
            row[21].zfill(8),
        ])

brzesc = pd.DataFrame(results, columns=[
    'name',
    'city',
    'gender',
    'team',
    'category',
    'result_brzesc',
])

fixes = [
    ('team', 'T.G. SOKÓŁ', 'T.G. SOKÓŁ GNIEWKOWO'),
    ('team', 'TG SOKÓŁ GNIEWOWO', 'T.G. SOKÓŁ GNIEWKOWO'),
    ('team', 'TG SOKÓŁ GNIEWKOWO', 'T.G. SOKÓŁ GNIEWKOWO'),
    ('team', 'SOKÓŁ GNIEWKOWO', 'T.G. SOKÓŁ GNIEWKOWO'),
    ('team', 'T.G.SOKÓŁ GNIEWKOWO', 'T.G. SOKÓŁ GNIEWKOWO'),
    ('team', 'T.G SOKÓŁ GNIEWKOWO', 'T.G. SOKÓŁ GNIEWKOWO'),
    ('team', 'T.G .SOKÓŁ', 'T.G. SOKÓŁ GNIEWKOWO'),
    ('team', 'DRUŻYNA ROZBIEGANI LUBRANIEC', 'ROZBIEGANI LUBRANIEC'),
    ('team', 'PARKRUN  TORUŃ', 'PARKRUN TORUŃ'),
    ('team', 'PARKUN TORUŃ', 'PARKRUN TORUŃ'),
    ('team', 'PARKRUN NOWY PARK SOLANKOWY, INOWROCŁAW', 'PARKRUN NOWY PARK SOLANKOWY INOWROCŁAW'),
    ('team', 'KUNA  TEAM WŁOCŁAWEK', 'KUNA TEAM WŁOCŁAWEK'),
    ('team', 'WATAHA ŁĄCZY NAS BIEGANIE', 'WATAHA - ŁĄCZY NAS BIEGANIE'),
    ('name', 'BLASZCZAK STANISLAW', 'BŁASZCZAK STANISŁAW'),
    ('name', 'JARZECKI SŁAWOMIR', 'JARZĘCKI SŁAWOMIR'),
    ('name', 'TOMASZEWSKI MILOSZ', 'TOMASZEWSKI MIŁOSZ'),
    ('name', 'ŻUCHOWSKI JOZEF', 'ŻUCHOWSKI JÓZEF'),
    ('name', 'WOJEWODA TOMEK', 'WOJEWODA TOMASZ'),
]
for field, from_, to_ in fixes:
    brzesc.loc[brzesc[field] == from_, field] = to_

brzesc.loc[(brzesc['name'] == 'LEWANDOWSKI MACIEJ') & (brzesc['city'] == 'LUBRANIEC'), 'name'] = 'LEWANDOWSKI MACIEJ (LUBRANIEC)'
brzesc

,name,city,gender,team,category,result_brzesc
0,TOMASZEWSKI MACIEJ,TORUN,M,GKS FABIANKI,M30,00:33:23
1,RATAJCZYK PRZEMYSŁAW,ALEKSANDRÓW KUJAWSKI,M,TKKF KOLEJARZ BYDGOSZCZ,M30,00:33:42
2,TOMASZEWSKI MIŁOSZ,TORUŃ,M,GKS FABIANKI,M30,00:34:34
3,KUNECKI DARIUSZ,WŁOCŁAWEK,M,KUNA TEAM WŁOCŁAWEK,M40,00:35:14
4,PIASECKI KRZYSZTOF,WŁOCŁAWEK,M,KUNA TEAM WŁOCŁAWEK,M30,00:35:14
...,...,...,...,...,...,...
195,PIEKUT STEFAN,PŁOCK,M,TKKF PŁOCK,M70,03:16:35
196,WIERSKI JAROSŁAW,MAŁA NIESZAWKA,M,KUJAWSKO-POMORSKIE,M50,03:16:35
197,KOŁUCKI STEFAN,WARSZAWA,M,SFORA BMK,M30,03:16:35
198,SADOWSKI ŁUKASZ,SŁUPNO,M,None,M30,03:16:36
199,ZIENTARA MARCIN,BYTOŃ,M,KS ZRYW RADZIEJÓW,M40,03:16:36

In [21]:
after_5 = after_4.merge(brzesc, on=['name', 'gender'], how='outer', suffixes=('_base', '_brzesc'))

In [22]:
diff(after_5, 'team', ('_base', '_brzesc')) # OK!

,name,gender,result_torun,result_grudziadz,result_fabianki,year_of_birth,result_waganiec,team_base,category_base,city_base,city_brzesc,team_brzesc,category_brzesc,result_brzesc
62,BĄBIŃSKI BARTŁOMIEJ,M,NaN,NaN,00:41:20,1976,00:41:21,BBG-PROJEKT,M50,WŁOCŁAWEK,WŁOCŁAWEK,WKB MARATOŃCZYK,M50,00:42:42
66,BŁASZCZAK STANISŁAW,M,NaN,01:19:28,01:14:40,1946,01:16:22,WKB MARATOŃCZYK WŁOCŁAWEK,M80,SKĘPE,SKEPE,WKB MARATONCZYK WLOCLAWEK,M70,01:15:25
311,KLIMEK WIKTOR,M,NaN,NaN,00:47:26,2007,00:46:51,KRUKOWO,M16,CHOCEŃ,KRUKOWO,KUNA TEAM WŁOCŁAWEK,M16,00:47:01
356,KRYSZAK KLAUDIA,K,NaN,NaN,00:49:46,1994,NaN,INOWROCŁAW,K30,NaN,INOWROCŁAW,T.G. SOKÓŁ GNIEWKOWO,K30,00:50:53
557,PRĄTNICKI WIESŁAW,M,NaN,NaN,00:46:59,1963,00:48:10,WŁOCŁAWEK,M60,WŁOCŁAWEK,WŁOCŁAWEK,ANWILTEAM,M60,00:47:14

In [23]:
diff(after_5, 'city', ('_base', '_brzesc')) # more or less OK!

,name,gender,result_torun,result_grudziadz,result_fabianki,year_of_birth,result_waganiec,team_base,category_base,city_base,city_brzesc,team_brzesc,category_brzesc,result_brzesc
66,BŁASZCZAK STANISŁAW,M,NaN,01:19:28,01:14:40,1946,01:16:22,WKB MARATOŃCZYK WŁOCŁAWEK,M80,SKĘPE,SKEPE,WKB MARATONCZYK WLOCLAWEK,M70,01:15:25
93,CISKI ZBIGNIEW,M,00:56:29,00:55:18,00:52:27,1963,NaN,ZABIEGANI ŁUBIANKA,M60,TORUŃ,TORU,None,M60,00:53:53
104,CZERENKIEWICZ-PAŁUCKA JOANNA,K,00:47:31,00:49:23,00:46:53,1975,00:48:07,KUNA TEAM WŁOCŁAWEK,K50,WŁOCŁAWEK,MACHNACZ,KUNA TEAM WŁOCŁAWEK,K50,00:47:42
165,GABIZDALSKA ALICJA,K,00:57:36,00:58:10,00:53:07,1999,NaN,T.G. SOKÓŁ GNIEWKOWO,K16,OSTROWO,GNIEWKOWO,T.G. SOKÓŁ GNIEWKOWO,K20,00:56:08
167,GAC MONIKA,K,00:49:23,00:51:39,00:48:31,1976,00:49:11,T.G. SOKÓŁ GNIEWKOWO,K50,TORUŃ,GNIEWKOWO,T.G. SOKÓŁ GNIEWKOWO,K50,00:50:38
177,GERKA KRZYSZTOF,M,NaN,01:22:03,01:14:02,1957,01:26:41,RKS LECH RYPIN,M65,BRZUZE,RYPIN,RKS LECH RYPIN,M60,01:24:20
260,JARZĘCKI SŁAWOMIR,M,NaN,NaN,NaN,NaN,00:47:39,KUNA TEAM,M50,BRZESC KUJAWSKI,MARIANKI,KUNA TEAM,M50,00:48:14
311,KLIMEK WIKTOR,M,NaN,NaN,00:47:26,2007,00:46:51,KRUKOWO,M16,CHOCEŃ,KRUKOWO,KUNA TEAM WŁOCŁAWEK,M16,00:47:01
406,LEWANDOWSKI WŁADYSŁAW,M,01:00:34,01:03:56,00:56:02,1954,00:54:47,T.G. SOKÓŁ GNIEWKOWO,M70,INOWROCŁAW,JANIKOWO,T.G. SOKÓŁ GNIEWKOWO,M70,00:53:39
484,NOWAK MARCIN,M,00:48:21,00:49:29,00:46:54,1979,00:47:52,BĄDKOWO,M40,BADKOWO,BĄDKOWO,None,M40,00:47:07
494,OLSZEWSKI ADAM,M,NaN,00:53:20,00:55:41,1963,00:54:19,RKS LECH RYPIN,M60,ROGOWO,RYPIN,RKS LECH RYPIN,M60,00:50:43
661,SZTENDEREWICZ RENATA,K,00:45:44,NaN,00:45:38,1982,NaN,KUNA TEAM WŁOCŁAWEK,K40,WŁOCŁAWEK (RYBNICA),WŁOCŁAWEK,KUNA TEAM WŁOCŁAWEK,K40,00:47:11
686,TOMASZEWSKI MACIEJ,M,00:32:41,00:35:01,00:33:04,1988,00:33:00,GKS FABIANKI,M30,TORUŃ,TORUN,GKS FABIANKI,M30,00:33:23
735,WIŚNIEWSKI DAMIAN,M,00:43:44,NaN,00:42:54,1987,00:44:02,KUJAWSKO-POMORSKIE,,,TORUŃ,KUJAWSKO-POMORSKIE,M30,00:43:30
744,WOJEWODA TOMASZ,M,NaN,NaN,00:46:12,1983,00:46:11,PARKRUN TORUŃ,M40,TORUŃ,TOTUŃ,PARKRUN TORUŃ,M40,00:45:12
781,ZIÓŁKOWSKA NATALIA,K,NaN,NaN,00:47:56,1987,00:47:27,ZABIEGANI ŁUBIANKA,K30,PIGŻA,"ZAGONOWA, 7",ZABIEGANI ŁUBIANKA,K30,00:46:38

In [24]:
diff(after_5, 'category', ('_base', '_brzesc')) # more or less OK!

,name,gender,result_torun,result_grudziadz,result_fabianki,year_of_birth,result_waganiec,team_base,category_base,city_base,city_brzesc,team_brzesc,category_brzesc,result_brzesc
25,BEREBECKI ROMAN,M,NaN,00:50:29,00:49:01,1951,00:49:09,RKS LECH RYPIN,M75,RYPIN,RYPIN,RKS LECH RYPIN,M70,00:48:40
66,BŁASZCZAK STANISŁAW,M,NaN,01:19:28,01:14:40,1946,01:16:22,WKB MARATOŃCZYK WŁOCŁAWEK,M80,SKĘPE,SKEPE,WKB MARATONCZYK WLOCLAWEK,M70,01:15:25
96,CZAJKOWSKA ALEKSANDRA,K,01:02:04,00:59:37,00:55:35,1997,00:58:55,BYDGOSZCZ,K16,BYDGOSZCZ,BYDGOSZCZ,None,K20,00:54:41
113,DANIELEWICZ DARIA,K,00:48:31,00:47:53,NaN,1998,NaN,T.G. SOKÓŁ GNIEWKOWO,K16,GNIEWKOWO,GNIEWKOWO,T.G. SOKÓŁ GNIEWKOWO,K20,00:48:03
150,DŁONIAK EDMUND,M,01:06:27,01:06:05,01:03:58,1945,01:04:38,T.G. SOKÓŁ GNIEWKOWO,M80,GNIEWKOWO,GNIEWKOWO,T.G. SOKÓŁ GNIEWKOWO,M70,01:03:52
165,GABIZDALSKA ALICJA,K,00:57:36,00:58:10,00:53:07,1999,NaN,T.G. SOKÓŁ GNIEWKOWO,K16,OSTROWO,GNIEWKOWO,T.G. SOKÓŁ GNIEWKOWO,K20,00:56:08
177,GERKA KRZYSZTOF,M,NaN,01:22:03,01:14:02,1957,01:26:41,RKS LECH RYPIN,M65,BRZUZE,RYPIN,RKS LECH RYPIN,M60,01:24:20
305,KIPRIJANOVSKI WIKTORIA,K,NaN,NaN,00:39:13,2001,00:38:51,KUJAWSKO-POMORSKIE,K16,TORUN,TORUN,KUJAWSKO-POMORSKIE,K20,00:39:31
471,MĄCZKA ZBIGNIEW,M,00:48:11,00:47:38,00:46:59,1957,00:49:26,PARKRUN TORUŃ,M65,TORUŃ,TORUŃ,PARKRUN TORUŃ,M60,00:47:58
538,PIONTEK ELŻBIETA,K,01:01:58,01:06:59,NaN,1957,NaN,NaN,K65,BYDGOSZCZ,BYDGOSZCZ,None,K60,01:01:55
539,PIOTROWICZ IRENEUSZ,M,NaN,00:55:41,00:52:08,1960,00:53:35,PIOTRKÓW KUJAWSKI,M65,PIOTRKÓW KUJAWSKI,PIOTRKÓW KUJAWSKI,None,M60,00:53:58
626,SOWIŃSKI EDMUND,M,01:03:06,01:04:06,NaN,1942,01:03:28,TKKF PŁOCK,M80,PŁOCK,PŁOCK,TKKF PŁOCK,M70,01:03:26
735,WIŚNIEWSKI DAMIAN,M,00:43:44,NaN,00:42:54,1987,00:44:02,KUJAWSKO-POMORSKIE,,,TORUŃ,KUJAWSKO-POMORSKIE,M30,00:43:30
808,ŻYŁKOWSKA KRYSTYNA,K,00:51:36,00:54:53,00:51:38,1960,NaN,PARKRUN TORUŃ,K65,TORUN,TORUN,PARKRUN TORUŃ,K60,00:53:48

In [25]:
after_5['team'] = after_5['team_base'].combine_first(after_5['team_brzesc'])
after_5['category'] = after_5['category_base'].combine_first(after_5['category_brzesc'])
after_5['city'] = after_5['city_base'].combine_first(after_5['city_brzesc'])
after_5 = after_5.drop(labels=['team_base', 'team_brzesc', 'category_brzesc', 'category_base', 'city_base', 'city_brzesc'], axis=1)
after_5

,name,gender,result_torun,result_grudziadz,result_fabianki,year_of_birth,result_waganiec,result_brzesc,team,category,city
0,ADAMCZYK ZBIGNIEW,M,01:18:02,NaN,NaN,NaN,NaN,NaN,ZABIEGANI ŁUBIANKA,M70,ZAMEK BIERZGŁOWSKI
1,AFTYKA TOMASZ,M,00:50:03,NaN,NaN,NaN,NaN,NaN,RTR,M50,GRUDZIĄDZ
2,AGUADO OREGUI LIDIA,K,00:49:55,NaN,NaN,NaN,NaN,NaN,NaN,K20,TORUŃ
3,ANDRZEJCZAK KRYSTIAN,M,NaN,NaN,NaN,NaN,NaN,00:43:26,None,M30,BRZEŚĆ KUJAWSKI
4,ANDRZEJCZAK MACIEJ,M,00:42:21,NaN,NaN,NaN,NaN,NaN,ZESPÓŁ SZKÓŁ IM. JADWIGI GRODZKIEJ,M16,ŁĘCZYCA
...,...,...,...,...,...,...,...,...,...,...,...
805,ŻUCHOWSKI JÓZEF,M,NaN,NaN,00:40:32,1971,00:41:43,00:41:19,PŁONNE,M50,RADOMIN
806,ŻUCHOWSKI RADOSŁAW,M,00:55:10,NaN,NaN,NaN,NaN,NaN,NaN,M30,TORUŃ
807,ŻYŁA JUSTYNA,K,NaN,00:50:27,NaN,1977,NaN,NaN,LA RIVE SPORT TEAM,K40,NaN
808,ŻYŁKOWSKA KRYSTYNA,K,00:51:36,00:54:53,00:51:38,1960,NaN,00:53:48,PARKRUN TORUŃ,K65,TORUN
809,ŻÓRAWSKA BARBARA,K,01:03:45,NaN,NaN,NaN,NaN,NaN,NaN,K20,WARSZAWA

# Unisław

```
curl 'https://live.sts-timing.pl/unislaw2026/api.php?action=load-more-results&i=0&d=1&p=false' > unislaw.json 
```

In [38]:
html = '<table>'
with open('unislaw.json') as f:
    for line in f.readlines():
        html += json.loads(line)['html']

html += '</table>'
table = html_to_json.convert_tables(html)[0]
unislaw = pd.DataFrame(table, columns=[
    'place',
    'bib',
    'name',
    'country',
    'city',
    'team',
    'gender',
    '_c0',
    'category',
    '_c1',
    'result_unislaw',
    '_c2',
    '_c3'
])

unislaw = unislaw[['name', 'city', 'team', 'gender', 'result_unislaw', 'category']]
unislaw['name'] = unislaw['name'].str.upper()
unislaw['city'] = unislaw['city'].str.upper()
unislaw['team'] = unislaw['team'].str.upper().replace('', None)
unislaw['result_unislaw'] = unislaw['result_unislaw'].str.zfill(8).replace('^000', '00:', regex=True)

fixes = [
    ('team', 'TG SOKÓŁ GNIEWKOWO', 'T.G. SOKÓŁ GNIEWKOWO'),
    ('team', 'PARKRUN  TORUŃ', 'PARKRUN TORUŃ'),
    ('team', 'KUNA TEAM WLOCLAWEK', 'KUNA TEAM WŁOCŁAWEK'),
    ('team', 'PARKRUN', 'PARKRUN TORUŃ'),
    ('name', 'BLASZCZAK STANISLAW', 'BŁASZCZAK STANISŁAW'),
    ('name', 'JABŁONSKI JAROSLAW', 'JABŁOŃSKI JAROSŁAW'),
    ('team', 'PARKRUN TORUN', 'PARKRUN TORUŃ'),
]
for field, from_, to_ in fixes:
    unislaw.loc[unislaw[field] == from_, field] = to_

unislaw.loc[(unislaw['name'] == 'ZIELIŃSKI MAREK') & (unislaw['city'] == 'PRZECZNO'), 'name'] = 'ZIELIŃSKI MAREK (PRZECZNO)'
unislaw.loc[(unislaw['name'] == 'KALOTA JOANNA'), 'gender'] = 'K'
    
unislaw

,name,city,team,gender,result_unislaw,category
0,PRZYBYŁA ADRIAN,IŁAWA,RUN GOKU TEAM,M,00:32:55,M30
1,RATAJCZYK PRZEMYSŁAW,ALEKSANDRÓW KUJAWSKI,TKKF KOLEJARZ BYDGOSZCZ,M,00:33:25,M30
2,TOMASZEWSKI MACIEJ,TORUŃ,GKS FABIANKI,M,00:34:48,M30
3,KLEDZIK ZBIGNIEW,KIERZKOWO,PAŁUKI RUNNING TEAM,M,00:35:00,M30
4,PIASECKI KRZYSZTOF,WŁOCŁAWEK,KUNA TEAM WŁOCŁAWEK,M,00:36:27,M30
...,...,...,...,...,...,...
278,SZTENDEREWICZ RENATA,WŁOCŁAWEK (RYBNICA),KUNA TEAM WŁOCŁAWEK,K,01:34:35,K40
279,TOMASZEWSKI MIŁOSZ,TORUN,None,M,01:35:25,M30
280,ŚWIADEK MACIEJ,UNISŁAW,None,M,01:40:23,M16
281,ADAMCZYK ZBIGNIEW,ZAMEK BIERZGŁOWSKI,ZABIEGANI ŁUBIANKA,M,01:51:46,M70
282,MAJEWSKI JAN,TORUŃ,TKKF TORUŃ,M,01:51:49,M70

In [39]:
after_6 = after_5.merge(unislaw, on=['name', 'gender'], how='outer', suffixes=('_base', '_unislaw'))

In [40]:
diff(after_6, 'team', ('_base', '_unislaw')) # OK

,name,gender,result_torun,result_grudziadz,result_fabianki,year_of_birth,result_waganiec,result_brzesc,team_base,category_base,city_base,city_unislaw,team_unislaw,result_unislaw,category_unislaw
74,BŁASZCZAK STANISŁAW,M,NaN,01:19:28,01:14:40,1946,01:16:22,01:15:25,WKB MARATOŃCZYK WŁOCŁAWEK,M80,SKĘPE,SKEPE,WKB MARATONCZYK WLOVLAWEK,01:21:47,M70
82,CHMIELARZ SEBASTIAN,M,NaN,NaN,00:43:06,1987,NaN,NaN,CHMIELARZ TEAM / ZALINIAMETY,M30,NaN,KRUSZWICA,PARKRUN TORUŃ,00:43:10,M30
293,JARZĘCKI SŁAWOMIR,M,NaN,NaN,NaN,NaN,00:47:39,00:48:14,KUNA TEAM,M50,BRZESC KUJAWSKI,BRZEŚ? KUJAWSKI,KUNA TEAM WŁOCŁAWEK,00:50:04,M50
409,KRYSZAK KLAUDIA,K,NaN,NaN,00:49:46,1994,NaN,00:50:53,INOWROCŁAW,K30,INOWROCŁAW,INOWROCLAW,T.G. SOKÓŁ GNIEWKOWO,00:50:49,K30

In [41]:
diff(after_6, 'city', ('_base', '_unislaw')) # quite OK

,name,gender,result_torun,result_grudziadz,result_fabianki,year_of_birth,result_waganiec,result_brzesc,team_base,category_base,city_base,city_unislaw,team_unislaw,result_unislaw,category_unislaw
74,BŁASZCZAK STANISŁAW,M,NaN,01:19:28,01:14:40,1946,01:16:22,01:15:25,WKB MARATOŃCZYK WŁOCŁAWEK,M80,SKĘPE,SKEPE,WKB MARATONCZYK WLOVLAWEK,01:21:47,M70
115,CZERENKIEWICZ-PAŁUCKA JOANNA,K,00:47:31,00:49:23,00:46:53,1975,00:48:07,00:47:42,KUNA TEAM WŁOCŁAWEK,K50,WŁOCŁAWEK,MACHNACZ,KUNA TEAM WŁOCŁAWEK,00:50:54,K50
187,GAC MONIKA,K,00:49:23,00:51:39,00:48:31,1976,00:49:11,00:50:38,T.G. SOKÓŁ GNIEWKOWO,K50,TORUŃ,GNIEWKOWO,T.G. SOKÓŁ GNIEWKOWO,00:56:24,K50
293,JARZĘCKI SŁAWOMIR,M,NaN,NaN,NaN,NaN,00:47:39,00:48:14,KUNA TEAM,M50,BRZESC KUJAWSKI,BRZEŚ? KUJAWSKI,KUNA TEAM WŁOCŁAWEK,00:50:04,M50
320,KALINOWSKA SYLWIA,K,00:55:47,NaN,NaN,NaN,00:58:39,NaN,NaN,K40,TORUŃ,TORUN,None,01:06:27,K40
409,KRYSZAK KLAUDIA,K,NaN,NaN,00:49:46,1994,NaN,00:50:53,INOWROCŁAW,K30,INOWROCŁAW,INOWROCLAW,T.G. SOKÓŁ GNIEWKOWO,00:50:49,K30
420,KUCHARSKI KRZYSZTOF,M,00:51:23,NaN,NaN,NaN,NaN,NaN,GP CROSS CHEŁMŻA,M40,BIELCZYNY,CHEŁMŻA,GP CROSS CHEŁMŻA,00:57:46,M40
467,LEWANDOWSKI ARTUR,M,00:50:48,NaN,00:47:07,1971,00:47:22,NaN,KUNA TEAM WŁOCŁAWEK,M50,WŁOCŁAWEK,SZPETAL GÓRNY,KUNA TEAM WŁOCŁAWEK,00:53:06,M50
630,PIKULSKA JOANNA,K,00:57:04,00:52:10,00:49:56,1988,00:52:19,00:50:24,KS ZRYW RADZIEJÓW,K30,LITYCHOWO,BYTOŃ,KS ZRYW RADZIEJÓW,00:45:38,K30
657,PRĄTNICKI WIESŁAW,M,NaN,NaN,00:46:59,1963,00:48:10,00:47:14,WŁOCŁAWEK,M60,WŁOCŁAWEK,WŁOCŁAWK,None,00:50:39,M60
808,TOMASZEWSKI MIŁOSZ,M,00:34:32,NaN,NaN,NaN,00:33:38,00:34:34,GKS FABIANKI,M30,TORUŃ,TORUN,None,01:35:25,M30
916,ZAWADZKI KRZYSZTOF,M,NaN,00:44:24,NaN,1974,00:45:04,NaN,BIEGOWI PRZYJACIELE,M50,ALEKSANDROW KUJAWSKI,CIECHOCINEK,BIEGOWI PRZYJACIELE,00:50:36,M50
936,ZYDLEWSKI SZYMON,M,00:40:32,NaN,NaN,NaN,NaN,NaN,NaN,M40,GDANSK,GDAŃSK,None,00:42:56,M40

In [42]:
diff(after_6, 'category', ('_base', '_unislaw')) # quite OK

,name,gender,result_torun,result_grudziadz,result_fabianki,year_of_birth,result_waganiec,result_brzesc,team_base,category_base,city_base,city_unislaw,team_unislaw,result_unislaw,category_unislaw
28,BEREBECKI ROMAN,M,NaN,00:50:29,00:49:01,1951,00:49:09,00:48:40,RKS LECH RYPIN,M75,RYPIN,RYPIN,None,00:55:14,M70
74,BŁASZCZAK STANISŁAW,M,NaN,01:19:28,01:14:40,1946,01:16:22,01:15:25,WKB MARATOŃCZYK WŁOCŁAWEK,M80,SKĘPE,SKEPE,WKB MARATONCZYK WLOVLAWEK,01:21:47,M70
75,BŁASZCZYK BARTOSZ,M,00:50:46,NaN,NaN,NaN,NaN,NaN,NaN,M20,UNISŁAW,UNISŁAW,None,00:55:43,M16
168,DŁONIAK EDMUND,M,01:06:27,01:06:05,01:03:58,1945,01:04:38,01:03:52,T.G. SOKÓŁ GNIEWKOWO,M80,GNIEWKOWO,GNIEWKOWO,T.G. SOKÓŁ GNIEWKOWO,01:07:36,M70
322,KALOTA JOANNA,K,NaN,00:38:54,00:37:04,1989,00:37:58,00:37:58,GKS FABIANKI,K30,TORUŃ,TORUŃ,GKS FABIANKI,00:38:59,M30
626,PIETRZAK MICHAŁ,M,00:35:51,NaN,00:36:42,2005,NaN,00:37:12,KUNA TEAM WŁOCŁAWEK,M20,WŁOCŁAWK,WŁOCŁAWK,KUNA TEAM WŁOCŁAWEK,00:40:09,M16
633,PIONTEK ELŻBIETA,K,01:01:58,01:06:59,NaN,1957,NaN,01:01:55,None,K65,BYDGOSZCZ,BYDGOSZCZ,None,01:07:53,K60
634,PIOTROWICZ IRENEUSZ,M,NaN,00:55:41,00:52:08,1960,00:53:35,00:53:58,PIOTRKÓW KUJAWSKI,M65,PIOTRKÓW KUJAWSKI,PIOTRKÓW KUJAWSKI,None,00:56:37,M60
701,RZĄD SZYMON,M,00:38:30,NaN,NaN,NaN,00:39:15,NaN,GRIT RC TORUŃ,M20,TORUŃ,TORUŃ,None,00:44:39,M16
739,SOWIŃSKI EDMUND,M,01:03:06,01:04:06,NaN,1942,01:03:28,01:03:26,TKKF PŁOCK,M80,PŁOCK,PŁOCK,TKKF PŁOCK,01:05:33,M70
796,SŁUNIECKA ALEKSANDRA,K,00:49:41,NaN,00:51:07,2002,00:51:05,00:51:20,PARKRUN TORUŃ,K20,TORUŃ,TORUŃ,PARKRUN TORUŃ,00:58:59,K16

In [43]:
after_6['team'] = after_6['team_base'].combine_first(after_6['team_unislaw'])
after_6['category'] = after_6['category_base'].combine_first(after_6['category_unislaw'])
after_6['city'] = after_6['city_base'].combine_first(after_6['city_unislaw'])
after_6 = after_6.drop(labels=['team_base', 'team_unislaw', 'category_unislaw', 'category_base', 'city_base', 'city_unislaw'], axis=1)
after_6

,name,gender,result_torun,result_grudziadz,result_fabianki,year_of_birth,result_waganiec,result_brzesc,result_unislaw,team,category,city
0,ADAMCZYK ZBIGNIEW,M,01:18:02,NaN,NaN,NaN,NaN,NaN,01:51:46,ZABIEGANI ŁUBIANKA,M70,ZAMEK BIERZGŁOWSKI
1,AFTYKA TOMASZ,M,00:50:03,NaN,NaN,NaN,NaN,NaN,NaN,RTR,M50,GRUDZIĄDZ
2,AGUADO OREGUI LIDIA,K,00:49:55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,K20,TORUŃ
3,ANDRZEJCZAK KRYSTIAN,M,NaN,NaN,NaN,NaN,NaN,00:43:26,NaN,NaN,M30,BRZEŚĆ KUJAWSKI
4,ANDRZEJCZAK MACIEJ,M,00:42:21,NaN,NaN,NaN,NaN,NaN,NaN,ZESPÓŁ SZKÓŁ IM. JADWIGI GRODZKIEJ,M16,ŁĘCZYCA
...,...,...,...,...,...,...,...,...,...,...,...,...
962,ŻUCHOWSKI RADOSŁAW,M,00:55:10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M30,TORUŃ
963,ŻYWIEŃ TOMASZ,M,NaN,NaN,NaN,NaN,NaN,NaN,01:00:06,None,M40,TORUŃ
964,ŻYŁA JUSTYNA,K,NaN,00:50:27,NaN,1977,NaN,NaN,NaN,LA RIVE SPORT TEAM,K40,NaN
965,ŻYŁKOWSKA KRYSTYNA,K,00:51:36,00:54:53,00:51:38,1960,NaN,00:53:48,NaN,PARKRUN TORUŃ,K65,TORUN
966,ŻÓRAWSKA BARBARA,K,01:03:45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,K20,WARSZAWA

In [44]:
final = after_6

# Adjust teams

In [45]:
final.loc[final['name'] == 'CIESIELSKI MACIEJ', 'team'] = 'PARKRUN TORUŃ - niezgłoszony'
final.loc[final['name'] == 'BARCZ ANNA', 'team'] = 'PARKRUN TORUŃ - niezgłoszony'
final.loc[final['name'] == 'BARCZ MACIEJ', 'team'] = 'PARKRUN TORUŃ - niezgłoszony'
final.loc[final['name'] == 'KRUCZKOWSKI JAROSŁAW', 'team'] = 'PARKRUN TORUŃ - niezgłoszony'
final.loc[final['name'] == 'SZARWIŃSKI MARIUSZ', 'team'] = 'PARKRUN TORUŃ'
final.loc[final['name'] == 'RZĄD SZYMON', 'team'] = 'BIEGOWI PRZYJACIELE'
final.loc[final['name'] == 'ŁOPATA SZYMON', 'team'] = 'BIEGOWI PRZYJACIELE'
final.loc[final['name'] == 'BARTKOWSKI SŁAWOMIR', 'category'] = 'M50'

final[final['team'] == 'PARKRUN TORUŃ']

,name,gender,result_torun,result_grudziadz,result_fabianki,year_of_birth,result_waganiec,result_brzesc,result_unislaw,team,category,city
10,BAJEŃSKI DARIUSZ,M,00:50:12,NaN,NaN,NaN,NaN,NaN,NaN,PARKRUN TORUŃ,M30,TORUŃ
96,CIESIELSKI JAN,M,00:50:32,NaN,NaN,NaN,NaN,NaN,NaN,PARKRUN TORUŃ,M50,TORUŃ
132,DEPERAS ALEKSANDER,M,NaN,NaN,00:38:33,1984,NaN,NaN,00:43:04,PARKRUN TORUŃ,M40,TORUŃ
151,DUDKOWIAK MICHAŁ,M,00:47:46,NaN,00:46:20,1984,NaN,NaN,NaN,PARKRUN TORUŃ,M40,TORUŃ
167,DĘBICKI MACIEJ,M,00:42:52,00:42:43,00:41:33,1993,00:42:37,NaN,00:44:40,PARKRUN TORUŃ,M30,GOSTKOWO
181,FRĄCZYK ANNA,K,00:54:18,00:56:45,NaN,1980,NaN,NaN,NaN,PARKRUN TORUŃ,K40,TORUŃ
182,FRĄCZYK JAROSŁAW,M,00:52:02,00:49:01,NaN,1976,NaN,NaN,NaN,PARKRUN TORUŃ,M50,TORUŃ
183,FRĄK EDYTA,K,00:42:36,00:43:43,00:41:39,1988,NaN,00:42:05,NaN,PARKRUN TORUŃ,K30,TORUŃ
209,GODLEWSKI KRZYSZTOF,M,00:47:11,00:47:47,00:45:51,1977,00:46:23,00:45:52,00:52:24,PARKRUN TORUŃ,M40,TORUŃ
213,GOŁĘBIEWSKI MICHAŁ,M,00:42:15,NaN,00:41:19,1983,NaN,NaN,00:44:00,PARKRUN TORUŃ,M40,TORUŃ
263,HUSSEIN ABDALLA,M,00:42:23,00:43:09,00:41:52,1987,00:42:13,00:42:17,00:43:14,PARKRUN TORUŃ,M30,KONRADOWO
264,HUSSEIN ANNA,K,00:48:29,00:51:42,00:48:28,1981,00:49:38,00:49:10,00:56:24,PARKRUN TORUŃ,K40,KONRADOWO
272,JABŁOŃSKA MAGDALENA,K,NaN,NaN,NaN,NaN,NaN,NaN,00:56:02,PARKRUN TORUŃ,K40,TORUŃ
273,JABŁOŃSKI DOMINIK,M,00:41:07,00:42:12,00:40:26,1980,00:41:57,NaN,00:44:22,PARKRUN TORUŃ,M40,TORUŃ
281,JANECZKO KATARZYNA,K,NaN,00:57:22,NaN,1982,00:53:18,00:54:12,00:57:20,PARKRUN TORUŃ,K40,TORUŃ
284,JANISZEWSKI DAREK,M,NaN,NaN,NaN,NaN,NaN,00:52:44,NaN,PARKRUN TORUŃ,M50,TORUŃ
285,JANISZEWSKI DARIUSZ,M,00:51:03,00:53:59,NaN,1973,00:51:01,NaN,NaN,PARKRUN TORUŃ,M50,TORUŃ
299,JAWORSKI JAROSŁAW,M,00:53:08,00:57:51,NaN,1971,00:50:00,00:49:15,NaN,PARKRUN TORUŃ,M50,TORUŃ
317,KACZOROWSKA ANNA,K,00:50:40,NaN,NaN,NaN,NaN,NaN,NaN,PARKRUN TORUŃ,K40,TORUŃ
321,KALINOWSKI ARKADIUSZ,M,00:49:29,00:50:18,00:47:56,1981,00:49:58,NaN,00:55:06,PARKRUN TORUŃ,M40,TORUŃ
363,KOPERSKI SEBASTIAN,M,NaN,00:58:52,NaN,1978,00:53:19,00:54:12,00:53:49,PARKRUN TORUŃ,M40,CZERNIKOWO
382,KOZICKI ROMAN,M,00:46:38,00:46:57,00:45:05,1967,00:46:46,00:46:28,01:24:00,PARKRUN TORUŃ,M50,TORUŃ
425,KUDŁA AGNIESZKA,K,00:53:33,00:53:55,NaN,1979,NaN,NaN,NaN,PARKRUN TORUŃ,K40,TORUŃ
491,LUBISZEWSKI ROBERT,M,00:48:31,00:48:44,NaN,1990,NaN,NaN,NaN,PARKRUN TORUŃ,M30,TORUŃ
523,MECHLIŃSKI BARTŁOMIEJ,M,NaN,00:38:47,00:37:42,1979,00:38:08,NaN,NaN,PARKRUN TORUŃ,M40,TORUŃ
530,MIEDZAK DAWID,M,00:44:43,00:45:04,00:43:45,1991,00:44:17,00:44:19,00:48:27,PARKRUN TORUŃ,M30,TORUŃ
531,MIEDZAK KAROL,M,00:42:06,NaN,00:43:41,1994,00:47:11,00:43:41,00:51:05,PARKRUN TORUŃ,M30,TORUŃ
541,MOLTZAN ŁUKASZ,M,NaN,NaN,00:45:44,1985,NaN,NaN,NaN,PARKRUN TORUŃ,M40,NaN
558,MĄCZKA MAŁGORZATA,K,NaN,NaN,01:17:39,1961,NaN,NaN,NaN,PARKRUN TORUŃ,K60,NaN
559,MĄCZKA ZBIGNIEW,M,00:48:11,00:47:38,00:46:59,1957,00:49:26,00:47:58,NaN,PARKRUN TORUŃ,M65,TORUŃ
585,OLSZEWSKI KAROL,M,00:44:53,NaN,NaN,NaN,NaN,00:43:20,NaN,PARKRUN TORUŃ,M40,TORUŃ
613,PAZDERSKA MAŁGORZATA,K,00:42:57,00:43:48,00:43:05,1985,00:45:00,00:44:18,00:48:09,PARKRUN TORUŃ,K40,TORUŃ
679,ROK-SZPALA SYLWIA,K,00:40:46,NaN,00:40:26,1981,00:41:38,00:41:21,00:41:51,PARKRUN TORUŃ,K40,LUBICZ GÓRNY
729,SMOLEŃ AGNIESZKA,K,NaN,NaN,01:01:12,1985,01:00:24,01:03:02,01:06:49,PARKRUN TORUŃ,K40,TORUŃ
749,STAWARSKA ELŻBIETA,K,NaN,00:52:14,00:49:51,1977,00:51:06,00:50:08,00:54:25,PARKRUN TORUŃ,K40,TORUŃ
756,STRZELECKI MARIUSZ,M,00:39:47,NaN,00:40:26,1987,00:42:17,00:42:49,NaN,PARKRUN TORUŃ,M30,BRZOZÓWKA
760,SYROCKA AGNIESZKA,K,01:04:19,01:03:00,01:00:21,1979,NaN,NaN,01:10:34,PARKRUN TORUŃ,K40,TORUŃ
766,SZARWIŃSKI MARIUSZ,M,00:43:19,NaN,00:42:05,1987,NaN,00:44:04,00:48:48,PARKRUN TORUŃ,M30,TORUŃ
787,SZYMAŃSKI JAROSŁAW,M,00:45:32,00:47:21,NaN,1979,NaN,00:45:14,00:52:32,PARKRUN TORUŃ,M40,TORUŃ
796,SŁUNIECKA ALEKSANDRA,K,00:49:41,NaN,00:51:07,2002,00:51:05,00:51:20,00:58:59,PARKRUN TORUŃ,K20,TORUŃ
797,SŁUNIECKI TOMASZ,M,00:42:45,NaN,00:41:39,1975,00:43:43,00:43:07,00:44:46,PARKRUN TORUŃ,M50,TORUŃ
822,TWAROWSKI ARKADIUSZ,M,NaN,NaN,NaN,NaN,NaN,NaN,00:49:15,PARKRUN TORUŃ,M40,TORUŃ
831,WALKOWIAK KRZYSZTOF,M,00:51:56,NaN,00:52:02,1990,NaN,NaN,01:00:16,PARKRUN TORUŃ,M30,TORUŃ
838,WASIECZKO MATEUSZ,M,00:54:20,00:55:55,NaN,1979,NaN,NaN,NaN,PARKRUN TORUŃ,M40,KOPANINO
843,WAWRZYNOWICZ SYLWESTER,M,NaN,NaN,NaN,NaN,00:41:39,00:41:08,00:45:05,PARKRUN TORUŃ,M40,TORUŃ
867,WIŚNIEWSKA DANIELA,K,00:53:07,NaN,00:52:36,1981,00:53:37,NaN,NaN,PARKRUN TORUŃ,K40,LUBICZ GÓRNY
871,WIŚNIEWSKI JAKUB,M,00:43:19,NaN,NaN,NaN,00:44:01,NaN,00:43:51,PARKRUN TORUŃ,M30,SILNO
878,WOJCIECHOWSKI PRZEMYSŁAW,M,00:39:30,00:40:12,00:39:30,1985,00:40:23,00:39:25,00:41:54,PARKRUN TORUŃ,M40,TORUŃ
879,WOJCIECHOWSKI SŁAWOMIR,M,00:58:33,NaN,NaN,NaN,00:59:03,00:56:48,01:06:16,PARKRUN TORUŃ,M40,LUBICZ DOLNY
880,WOJEWODA TOMASZ,M,NaN,NaN,00:46:12,1983,00:46:11,00:45:12,00:48:41,PARKRUN TORUŃ,M40,TORUŃ
896,WYSOCKI DARIUSZ,M,00:43:53,00:44:27,00:43:23,1986,00:44:34,00:44:25,00:47:10,PARKRUN TORUŃ,M40,TORUŃ
928,ZIÓŁKOWSKI GRZEGORZ,M,NaN,00:43:38,NaN,1985,00:44:28,00:44:26,00:45:59,PARKRUN TORUŃ,M40,TORUŃ
965,ŻYŁKOWSKA KRYSTYNA,K,00:51:36,00:54:53,00:51:38,1960,NaN,00:53:48,NaN,PARKRUN TORUŃ,K65,TORUN

In [46]:
# sorted(final[final['team'].notnull()]['team'].unique())

## Save

In [47]:
def to_seconds(time_str):
    t = datetime.time.fromisoformat(time_str)
    return t.hour * 3600 + t.minute * 60 + t.second

def to_time_str(seconds):
    return datetime.datetime.fromtimestamp(seconds, datetime.UTC).strftime('%T')

def gp_round(n):
    if n - math.floor(n) < 0.5:
        return math.floor(n)
    return math.ceil(n)

def get_result(row):
    results = [(col[len('result_'):], row[col]) for col in row.index if col.startswith('result_') and type(row[col]) == str]
    row['total_runs'] = len(results)
    best_6_runs = sorted([(r[0], to_seconds(r[1])) for r in results], key=lambda r: r[1])[:6]
    row['avg_result'] = gp_round(sum([r[1] for r in best_6_runs]) / len(best_6_runs))
    row['best_runs'] = ','.join(r[0] for r in best_6_runs)
    row['avg_result_str'] = to_time_str(row['avg_result'])
    return row

In [48]:
def get_category(row):
    if pd.isnull(row['year_of_birth']):
        return row

    if row['year_of_birth'] > year - 30:
        row['category'] = row['gender'] + '18'
    elif row['year_of_birth'] > year - 40:
        row['category'] = row['gender'] + '30'
    elif row['year_of_birth'] > year - 50:
        row['category'] = row['gender'] + '40'
    elif row['year_of_birth'] > year - 60:
        row['category'] = row['gender'] + '50'
    elif row['year_of_birth'] > year - 65:
        row['category'] = row['gender'] + '60'
    elif row['year_of_birth'] > year - 70:
        row['category'] = row['gender'] + '65'
    elif row['year_of_birth'] > year - 75:
        row['category'] = row['gender'] + '70'
    elif row['year_of_birth'] > year - 80:
        row['category'] = row['gender'] + '75'
    elif row['year_of_birth'] > year - 86:
        row['category'] = row['gender'] + '80'
    else:
        row['category'] = row['gender'] + '85'

    return row
        
gp = final.apply(get_result, axis=1)
gp['year_of_birth'] = gp['year_of_birth'].astype('Int64')
gp = gp.apply(get_category, axis=1)
gp

,name,gender,result_torun,result_grudziadz,result_fabianki,year_of_birth,result_waganiec,result_brzesc,result_unislaw,team,category,city,total_runs,avg_result,best_runs,avg_result_str
0,ADAMCZYK ZBIGNIEW,M,01:18:02,NaN,NaN,<NA>,NaN,NaN,01:51:46,ZABIEGANI ŁUBIANKA,M70,ZAMEK BIERZGŁOWSKI,2,5694,"torun,unislaw",01:34:54
1,AFTYKA TOMASZ,M,00:50:03,NaN,NaN,<NA>,NaN,NaN,NaN,RTR,M50,GRUDZIĄDZ,1,3003,torun,00:50:03
2,AGUADO OREGUI LIDIA,K,00:49:55,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,K20,TORUŃ,1,2995,torun,00:49:55
3,ANDRZEJCZAK KRYSTIAN,M,NaN,NaN,NaN,<NA>,NaN,00:43:26,NaN,NaN,M30,BRZEŚĆ KUJAWSKI,1,2606,brzesc,00:43:26
4,ANDRZEJCZAK MACIEJ,M,00:42:21,NaN,NaN,<NA>,NaN,NaN,NaN,ZESPÓŁ SZKÓŁ IM. JADWIGI GRODZKIEJ,M16,ŁĘCZYCA,1,2541,torun,00:42:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
962,ŻUCHOWSKI RADOSŁAW,M,00:55:10,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,M30,TORUŃ,1,3310,torun,00:55:10
963,ŻYWIEŃ TOMASZ,M,NaN,NaN,NaN,<NA>,NaN,NaN,01:00:06,None,M40,TORUŃ,1,3606,unislaw,01:00:06
964,ŻYŁA JUSTYNA,K,NaN,00:50:27,NaN,1977,NaN,NaN,NaN,LA RIVE SPORT TEAM,K40,NaN,1,3027,grudziadz,00:50:27
965,ŻYŁKOWSKA KRYSTYNA,K,00:51:36,00:54:53,00:51:38,1960,NaN,00:53:48,NaN,PARKRUN TORUŃ,K65,TORUN,4,3179,"torun,fabianki,brzesc,grudziadz",00:52:59
966,ŻÓRAWSKA BARBARA,K,01:03:45,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,K20,WARSZAWA,1,3825,torun,01:03:45

In [49]:
gp.to_sql(name='results', con=cnx, if_exists='replace', index_label='id')

967