In [1]:
import pandas as pd
import numpy as np
import json
import math
import sqlite3
import datetime
import html_to_json
year = 2026
pd.set_option('display.max_columns', None)
cnx = sqlite3.connect('results.db')

def diff(df, column, suffixes):
    c1 = column + suffixes[0]
    c2 = column + suffixes[1]
    return df[df[c1].notnull() & after_2[c2].notnull() & (after_2[c1] != after_2[c2])]

# Toruń

```
curl 'https://live.sts-timing.pl/TrylogiaTorunskichLegend/I/api.php?action=load-more-results&i=0&d=2&p=false&filtr=false' >> torun.json 
echo >> torun.json 
curl 'https://live.sts-timing.pl/TrylogiaTorunskichLegend/I/api.php?action=load-more-results&i=500&d=2&p=false&filtr=false' >> torun.json 
echo >> torun.json 
```

In [2]:
html = '<table>'
with open('torun.json') as f:
    for line in f.readlines():
        html += json.loads(line)['html']

html += '</table>'
table = html_to_json.convert_tables(html)[0]
torun = pd.DataFrame(table, columns=[
    'place',
    'bib',
    'name',
    'city',
    'team',
    'gender',
    '_c0',
    'category',
    '_c1',
    'gun_time',
    'result_torun',
    '_c2',
])
torun = torun[['name', 'city', 'team', 'gender', 'category', 'result_torun']]
torun['name'] = torun['name'].str.upper()
torun['city'] = torun['city'].str.upper()
torun['category'] = torun['category'].str.slice(0, 3)
torun['team'] = torun['team'].str.upper().replace('', None)

fixes = [
    ('name', 'KUDLA AGNIESZKA', 'KUDŁA AGNIESZKA'),
    ('team', 'ECIT NORIAN / PARKRUN TORUŃ', 'PARKRUN TORUŃ'),
    ('name', 'SZARWIŃSKI SZARWIŃSKI', 'SZARWIŃSKI MARIUSZ'),
    ('team', 'AKTYWNY  GRUDZIĄDZ', 'AKTYWNY GRUDZIĄDZ'),
    ('team', 'BIEGOWI PRZYJACIELE.', 'BIEGOWI PRZYJACIELE'),
    ('team', 'T.G.SOKÓŁ GNIEWKOWO', 'T.G. SOKÓŁ GNIEWKOWO'),
    ('team', 'TG SOKÓŁ GNIEWKOWO', 'T.G. SOKÓŁ GNIEWKOWO'),
    ('team', 'GWIAZDY NESTLÉ FITNESS', 'GWIAZDY NESTLE FITNESS'),
    ('team', 'SOKÓŁ GNIEWKOWO', 'T.G. SOKÓŁ GNIEWKOWO'),
    ('name', 'JABLONSKI JAROSLAW', 'JABŁOŃSKI JAROSŁAW'),
    ('name', 'LOPATA SZYMON', 'ŁOPATA SZYMON'),
    ('name', 'CZAJKOWSKI ALEKSANDRA', 'CZAJKOWSKA ALEKSANDRA'),
]
for field, from_, to_ in fixes:
    torun.loc[torun[field] == from_, field] = to_
    
torun

,name,city,team,gender,category,result_torun
0,RYNKOWSKI BARTOSZ,IŁAWA,None,M,M30,00:31:39
1,TOMASZEWSKI MACIEJ,TORUŃ,GKS FABIANKI,M,M30,00:32:41
2,RATAJCZYK PRZEMYSŁAW,ALEKSANDRÓW KUJAWSKI,TKKF KOLEJARZ BYDGOSZCZ,M,M30,00:33:15
3,SANKO ALIAKSANDR,GRUDZIĄDZ,None,M,M30,00:33:33
4,PIASECKI KRZYSZOF,WŁOCŁAWEK,KUNA TEAM WŁOCŁAWEK,M,M30,00:33:54
...,...,...,...,...,...,...
504,OLSZOWY NIKODEM,TORUŃ,None,M,M20,01:13:49
505,ŁAPIŃSKI SZYMON,TORUŃ,KLEJONT NOLU,M,M40,01:15:11
506,LIWIŃSKI SŁAWOMIR,SĘKOCIN-LAS,None,M,M50,01:16:55
507,KUŁAKOWSKI ROBERT,TORUŃ,HENDRICKSON POLAND,M,M50,01:17:31
508,ADAMCZYK ZBIGNIEW,ZAMEK BIERZGŁOWSKI,ZABIEGANI ŁUBIANKA,M,M70,01:18:02

# Grudziądz

In [3]:
# curl https://wyniki.domtel-sport.pl/zawody/5-bronek-run-forest-edition/ | grep ptc_vars > grudziadz.js
with open('grudziadz.js') as f:
    raw_data = json.loads(f.read()[15:-2])['init_data']

data = [
    [
        r['Zawodnik'],
        r['Team'],
        r['Płeć'],
        r['Kat'],
        r['Czas netto'],
        r['Rocz']
    ]
    for r in raw_data
    if r['DYSTANS'] == '10:59-10 km' and r['Msc']
]
grudziadz = pd.DataFrame(data, columns=['name', 'team', 'gender', 'category', 'result_grudziadz', 'year_of_birth'])
grudziadz['name'] = grudziadz['name'].str.upper()
grudziadz['team'] = grudziadz['team'].str.upper().replace('', None)
grudziadz

,name,team,gender,category,result_grudziadz,year_of_birth
0,DIDOVODIUK DMYTRO,None,M,M30,00:31:53,1987
1,WAŚKIEWICZ SEBASTIAN,KB BIEGAJĄCY DIETETYK TEAM,M,M30,00:34:05,1987
2,TOMASZEWSKI MACIEJ,GKS FABIANKI,M,M30,00:35:01,1988
3,JANKOWIAK DAREK,SAMISWOI,M,M30,00:35:36,1995
4,PETROW DANIEL,GRUDZIĄDZ,M,M40,00:36:41,1986
...,...,...,...,...,...,...
151,GRZESZAK DANUTA,None,K,K70,01:11:32,1953
152,LEWANDOWSKI WOJCIECH,None,M,M70,01:14:37,1952
153,BRAC-WALCZYK MAŁGORZATA,None,K,K65,01:16:56,1958
154,BŁASZCZAK STANISŁAW,WKB MARATOŃCZYK WŁOCŁAWEK,M,M80,01:19:28,1946
155,GERKA KRZYSZTOF,RKS LECH RYPIN,M,M65,01:22:03,1957

In [4]:
after_2 = torun.merge(grudziadz, on=['name', 'gender'], how='outer', suffixes=('_torun', '_grudziadz'))

In [5]:
diff(after_2, 'category', ('_torun', '_grudziadz')) # looks OK!

,name,city,team_torun,gender,category_torun,result_torun,team_grudziadz,category_grudziadz,result_grudziadz,year_of_birth
72,CZAJKOWSKA ALEKSANDRA,BYDGOSZCZ,None,K,K20,01:02:04,None,K16,00:59:37,1997
83,DANIELEWICZ DARIA,GNIEWKOWO,T.G. SOKÓŁ GNIEWKOWO,K,K20,00:48:31,T.G. SOKÓŁ GNIEWKOWO,K16,00:47:53,1998
110,DŁONIAK EDMUND,GNIEWKOWO,T.G. SOKÓŁ GNIEWKOWO,M,M70,01:06:27,T.G. SOKÓŁ GNIEWKOWO,M80,01:06:05,1945
124,GABIZDALSKA ALICJA,OSTROWO,T.G. SOKÓŁ GNIEWKOWO,K,K20,00:57:36,T.G. SOKÓŁ GNIEWKOWO,K16,00:58:10,1999
355,MĄCZKA ZBIGNIEW,TORUŃ,PARKRUN TORUŃ,M,M60,00:48:11,PARKRUN TORUŃ,M65,00:47:38,1957
408,PIONTEK ELŻBIETA,BYDGOSZCZ,None,K,K60,01:01:58,None,K65,01:06:59,1957
465,SOWIŃSKI EDMUND,PŁOCK,TKKF PŁOCK,M,M70,01:03:06,TKKF PŁOCK,M80,01:04:06,1942
606,ŻYŁKOWSKA KRYSTYNA,TORUN,PARKRUN TORUŃ,K,K60,00:51:36,PARKRUN TORUŃ,K65,00:54:53,1960

In [6]:
diff(after_2, 'team', ('_torun', '_grudziadz')) # looks OK!

,name,city,team_torun,gender,category_torun,result_torun,team_grudziadz,category_grudziadz,result_grudziadz,year_of_birth
571,WĄŻ SŁAWOMIR,GRĘBOCIN,GWIAZDY NESTLE FITNESS,M,M50,01:03:50,RCR,M50,01:01:34,1972
595,ŁOPATA SZYMON,PAPOWO TORUNSKIE,BIEGOWI PRZYJACIELE,M,M40,00:41:04,PAPOWO TORUŃSKIE,M40,00:42:57,1986

In [7]:
after_2['team'] = after_2['team_grudziadz'].combine_first(after_2['team_torun'])
after_2['category'] = after_2['category_grudziadz'].combine_first(after_2['category_torun'])
after_2 = after_2.drop(labels=['team_grudziadz', 'team_torun', 'category_grudziadz', 'category_torun'], axis=1)
after_2

,name,city,gender,result_torun,result_grudziadz,year_of_birth,team,category
0,ADAMCZYK ZBIGNIEW,ZAMEK BIERZGŁOWSKI,M,01:18:02,NaN,NaN,ZABIEGANI ŁUBIANKA,M70
1,AFTYKA TOMASZ,GRUDZIĄDZ,M,00:50:03,NaN,NaN,RTR,M50
2,AGUADO OREGUI LIDIA,TORUŃ,K,00:49:55,NaN,NaN,None,K20
3,ANDRZEJCZAK MACIEJ,ŁĘCZYCA,M,00:42:21,NaN,NaN,ZESPÓŁ SZKÓŁ IM. JADWIGI GRODZKIEJ,M16
4,ANTONOWICZ WOJCIECH,SZCZECIN,M,00:45:07,NaN,NaN,None,M60
...,...,...,...,...,...,...,...,...
603,ŻUCHOWSKA PAULINA,NaN,K,NaN,00:49:49,1996,AZS UMK TORUŃ,K30
604,ŻUCHOWSKI RADOSŁAW,TORUŃ,M,00:55:10,NaN,NaN,None,M30
605,ŻYŁA JUSTYNA,NaN,K,NaN,00:50:27,1977,LA RIVE SPORT TEAM,K40
606,ŻYŁKOWSKA KRYSTYNA,TORUN,K,00:51:36,00:54:53,1960,PARKRUN TORUŃ,K65
607,ŻÓRAWSKA BARBARA,WARSZAWA,K,01:03:45,NaN,NaN,None,K20

In [8]:
final = after_2

# Adjust teams

In [9]:
final.loc[final['name'] == 'CIESIELSKI MACIEJ', 'team'] = 'PARKRUN TORUŃ - niezgłoszony'
final.loc[final['name'] == 'BARCZ ANNA', 'team'] = 'PARKRUN TORUŃ - niezgłoszony'
final.loc[final['name'] == 'BARCZ MACIEJ', 'team'] = 'PARKRUN TORUŃ - niezgłoszony'
final.loc[final['name'] == 'KRUCZKOWSKI JAROSŁAW', 'team'] = 'PARKRUN TORUŃ - niezgłoszony'
final.loc[final['name'] == 'SZARWIŃSKI MARIUSZ', 'team'] = 'PARKRUN TORUŃ'
final.loc[final['name'] == 'RZĄD SZYMON', 'team'] = 'BIEGOWI PRZYJACIELE'

final[final['team'] == 'PARKRUN TORUŃ']

,name,city,gender,result_torun,result_grudziadz,year_of_birth,team,category
6,BAJEŃSKI DARIUSZ,TORUŃ,M,00:50:12,NaN,NaN,PARKRUN TORUŃ,M30
63,CIESIELSKI JAN,TORUŃ,M,00:50:32,NaN,NaN,PARKRUN TORUŃ,M50
100,DUDKOWIAK MICHAŁ,TORUŃ,M,00:47:46,NaN,NaN,PARKRUN TORUŃ,M40
109,DĘBICKI MACIEJ,GOSTKOWO,M,00:42:52,00:42:43,1993,PARKRUN TORUŃ,M30
120,FRĄCZYK ANNA,TORUŃ,K,00:54:18,00:56:45,1980,PARKRUN TORUŃ,K40
121,FRĄCZYK JAROSŁAW,TORUŃ,M,00:52:02,00:49:01,1976,PARKRUN TORUŃ,M50
122,FRĄK EDYTA,TORUŃ,K,00:42:36,00:43:43,1988,PARKRUN TORUŃ,K30
138,GODLEWSKI KRZYSZTOF,TORUŃ,M,00:47:11,00:47:47,1977,PARKRUN TORUŃ,M40
142,GOŁĘBIEWSKI MICHAŁ,TORUŃ,M,00:42:15,NaN,NaN,PARKRUN TORUŃ,M40
177,HUSSEIN ABDALLA,KONRADOWO,M,00:42:23,00:43:09,1987,PARKRUN TORUŃ,M30
178,HUSSEIN ANNA,KONRADOWO,K,00:48:29,00:51:42,1981,PARKRUN TORUŃ,K40
183,JABŁOŃSKI DOMINIK,TORUŃ,M,00:41:07,00:42:12,1980,PARKRUN TORUŃ,M40
189,JANECZKO KATARZYNA,NaN,K,NaN,00:57:22,1982,PARKRUN TORUŃ,K40
192,JANISZEWSKI DARIUSZ,TORUŃ,M,00:51:03,00:53:59,1973,PARKRUN TORUŃ,M50
201,JAWORSKI JAROSŁAW,TORUŃ,M,00:53:08,00:57:51,1971,PARKRUN TORUŃ,M50
212,KACZOROWSKA ANNA,TORUŃ,K,00:50:40,NaN,NaN,PARKRUN TORUŃ,K40
216,KALINOWSKI ARKADIUSZ,TORUŃ,M,00:49:29,00:50:18,1981,PARKRUN TORUŃ,M40
238,KOPERSKI SEBASTIAN,NaN,M,NaN,00:58:52,1978,PARKRUN TORUŃ,M40
254,KOZICKI ROMAN,TORUŃ,M,00:46:38,00:46:57,1967,PARKRUN TORUŃ,M50
282,KUDŁA AGNIESZKA,TORUŃ,K,00:53:33,00:53:55,1979,PARKRUN TORUŃ,K40
320,LUBISZEWSKI ROBERT,TORUŃ,M,00:48:31,00:48:44,1990,PARKRUN TORUŃ,M30
335,MECHLIŃSKI BARTŁOMIEJ,NaN,M,NaN,00:38:47,1979,PARKRUN TORUŃ,M40
340,MIEDZAK DAWID,TORUŃ,M,00:44:43,00:45:04,1991,PARKRUN TORUŃ,M30
341,MIEDZAK KAROL,TORUŃ,M,00:42:06,NaN,NaN,PARKRUN TORUŃ,M30
355,MĄCZKA ZBIGNIEW,TORUŃ,M,00:48:11,00:47:38,1957,PARKRUN TORUŃ,M65
377,OLSZEWSKI KAROL,TORUŃ,M,00:44:53,NaN,NaN,PARKRUN TORUŃ,M40
394,PAZDERSKA MAŁGORZATA,TORUŃ,K,00:42:57,00:43:48,1985,PARKRUN TORUŃ,K40
430,ROK-SZPALA SYLWIA,LUBICZ GÓRNY,K,00:40:46,NaN,NaN,PARKRUN TORUŃ,K40
474,STAWARSKA ELŻBIETA,NaN,K,NaN,00:52:14,1977,PARKRUN TORUŃ,K40
477,STRZELECKI MARIUSZ,BRZOZÓWKA,M,00:39:47,NaN,NaN,PARKRUN TORUŃ,M30
481,SYROCKA AGNIESZKA,TORUŃ,K,01:04:19,01:03:00,1979,PARKRUN TORUŃ,K40
485,SZARWIŃSKI MARIUSZ,TORUŃ,M,00:43:19,NaN,NaN,PARKRUN TORUŃ,M30
496,SZYMAŃSKI JAROSŁAW,TORUŃ,M,00:45:32,00:47:21,1979,PARKRUN TORUŃ,M40
501,SŁUNIECKA ALEKSANDRA,TORUŃ,K,00:49:41,NaN,NaN,PARKRUN TORUŃ,K20
502,SŁUNIECKI TOMASZ,TORUŃ,M,00:42:45,NaN,NaN,PARKRUN TORUŃ,M50
527,WALKOWIAK KRZYSZTOF,TORUŃ,M,00:51:56,NaN,NaN,PARKRUN TORUŃ,M30
533,WASIECZKO MATEUSZ,KOPANINO,M,00:54:20,00:55:55,1979,PARKRUN TORUŃ,M40
553,WIŚNIEWSKA DANIELA,LUBICZ GÓRNY,K,00:53:07,NaN,NaN,PARKRUN TORUŃ,K40
556,WIŚNIEWSKI JAKUB,SILNO,M,00:43:19,NaN,NaN,PARKRUN TORUŃ,M30
560,WOJCIECHOWSKI PRZEMYSŁAW,TORUŃ,M,00:39:30,00:40:12,1985,PARKRUN TORUŃ,M40
561,WOJCIECHOWSKI SŁAWOMIR,LUBICZ DOLNY,M,00:58:33,NaN,NaN,PARKRUN TORUŃ,M40
570,WYSOCKI DARIUSZ,TORUŃ,M,00:43:53,00:44:27,1986,PARKRUN TORUŃ,M40
587,ZIÓŁKOWSKI GRZEGORZ,NaN,M,NaN,00:43:38,1985,PARKRUN TORUŃ,M40
606,ŻYŁKOWSKA KRYSTYNA,TORUN,K,00:51:36,00:54:53,1960,PARKRUN TORUŃ,K65

In [10]:
# sorted(final[final['team'].notnull()]['team'].unique())

## Save

In [11]:
def to_seconds(time_str):
    t = datetime.time.fromisoformat(time_str)
    return t.hour * 3600 + t.minute * 60 + t.second

def to_time_str(seconds):
    return datetime.datetime.fromtimestamp(seconds, datetime.UTC).strftime('%T')

def gp_round(n):
    if n - math.floor(n) < 0.5:
        return math.floor(n)
    return math.ceil(n)

def get_result(row):
    results = [(col[len('result_'):], row[col]) for col in row.index if col.startswith('result_') and type(row[col]) == str]
    row['total_runs'] = len(results)
    best_6_runs = sorted([(r[0], to_seconds(r[1])) for r in results], key=lambda r: r[1])[:6]
    row['avg_result'] = gp_round(sum([r[1] for r in best_6_runs]) / len(best_6_runs))
    row['best_runs'] = ','.join(r[0] for r in best_6_runs)
    row['avg_result_str'] = to_time_str(row['avg_result'])
    return row

In [12]:
def get_category(row):
    if pd.isnull(row['year_of_birth']):
        return row

    if row['year_of_birth'] > year - 30:
        row['category'] = row['gender'] + '18'
    elif row['year_of_birth'] > year - 40:
        row['category'] = row['gender'] + '30'
    elif row['year_of_birth'] > year - 50:
        row['category'] = row['gender'] + '40'
    elif row['year_of_birth'] > year - 60:
        row['category'] = row['gender'] + '50'
    elif row['year_of_birth'] > year - 65:
        row['category'] = row['gender'] + '60'
    elif row['year_of_birth'] > year - 70:
        row['category'] = row['gender'] + '65'
    elif row['year_of_birth'] > year - 75:
        row['category'] = row['gender'] + '70'
    elif row['year_of_birth'] > year - 80:
        row['category'] = row['gender'] + '75'
    elif row['year_of_birth'] > year - 86:
        row['category'] = row['gender'] + '80'
    else:
        row['category'] = row['gender'] + '85'

    return row
        
gp = final.apply(get_result, axis=1)
gp['year_of_birth'] = gp['year_of_birth'].astype('Int64')
gp = gp.apply(get_category, axis=1)
gp

,name,city,gender,result_torun,result_grudziadz,year_of_birth,team,category,total_runs,avg_result,best_runs,avg_result_str
0,ADAMCZYK ZBIGNIEW,ZAMEK BIERZGŁOWSKI,M,01:18:02,NaN,<NA>,ZABIEGANI ŁUBIANKA,M70,1,4682,torun,01:18:02
1,AFTYKA TOMASZ,GRUDZIĄDZ,M,00:50:03,NaN,<NA>,RTR,M50,1,3003,torun,00:50:03
2,AGUADO OREGUI LIDIA,TORUŃ,K,00:49:55,NaN,<NA>,None,K20,1,2995,torun,00:49:55
3,ANDRZEJCZAK MACIEJ,ŁĘCZYCA,M,00:42:21,NaN,<NA>,ZESPÓŁ SZKÓŁ IM. JADWIGI GRODZKIEJ,M16,1,2541,torun,00:42:21
4,ANTONOWICZ WOJCIECH,SZCZECIN,M,00:45:07,NaN,<NA>,None,M60,1,2707,torun,00:45:07
...,...,...,...,...,...,...,...,...,...,...,...,...
603,ŻUCHOWSKA PAULINA,NaN,K,NaN,00:49:49,1996,AZS UMK TORUŃ,K30,1,2989,grudziadz,00:49:49
604,ŻUCHOWSKI RADOSŁAW,TORUŃ,M,00:55:10,NaN,<NA>,None,M30,1,3310,torun,00:55:10
605,ŻYŁA JUSTYNA,NaN,K,NaN,00:50:27,1977,LA RIVE SPORT TEAM,K40,1,3027,grudziadz,00:50:27
606,ŻYŁKOWSKA KRYSTYNA,TORUN,K,00:51:36,00:54:53,1960,PARKRUN TORUŃ,K65,2,3195,"torun,grudziadz",00:53:15
607,ŻÓRAWSKA BARBARA,WARSZAWA,K,01:03:45,NaN,<NA>,None,K20,1,3825,torun,01:03:45

In [13]:
gp.to_sql(name='results', con=cnx, if_exists='replace', index_label='id')

608