In [1]:
import pandas as pd
import numpy as np
import json
import math
import sqlite3
import datetime
import html_to_json
year = 2026
pd.set_option('display.max_columns', None)
cnx = sqlite3.connect('results.db')

# Toruń

```
curl 'https://live.sts-timing.pl/TrylogiaTorunskichLegend/I/api.php?action=load-more-results&i=0&d=2&p=false&filtr=false' >> torun.json 
echo >> torun.json 
curl 'https://live.sts-timing.pl/TrylogiaTorunskichLegend/I/api.php?action=load-more-results&i=500&d=2&p=false&filtr=false' >> torun.json 
echo >> torun.json 
```

In [2]:
html = '<table>'
with open('torun.json') as f:
    for line in f.readlines():
        html += json.loads(line)['html']

html += '</table>'
table = html_to_json.convert_tables(html)[0]
torun = pd.DataFrame(table, columns=[
    'place',
    'bib',
    'name',
    'city',
    'team',
    'gender',
    '_c0',
    'category',
    '_c1',
    'gun_time',
    'result_torun',
    '_c2',
])
torun = torun[['name', 'city', 'team', 'gender', 'category', 'result_torun']]
torun['name'] = torun['name'].str.upper()
torun['city'] = torun['city'].str.upper()
torun['team'] = torun['team'].str.upper().replace('', None)
torun['year_of_birth'] = np.nan

fixes = [
    ('name', 'KUDLA AGNIESZKA', 'KUDŁA AGNIESZKA'),
    ('team', 'ECIT NORIAN / PARKRUN TORUŃ', 'PARKRUN TORUŃ'),
    ('name', 'SZARWIŃSKI SZARWIŃSKI', 'SZARWIŃSKI MARIUSZ'),
    ('team', 'AKTYWNY  GRUDZIĄDZ', 'AKTYWNY GRUDZIĄDZ'),
    ('team', 'BIEGOWI PRZYJACIELE.', 'BIEGOWI PRZYJACIELE'),
    ('team', 'T.G.SOKÓŁ GNIEWKOWO', 'T.G. SOKÓŁ GNIEWKOWO'),
    ('team', 'TG SOKÓŁ GNIEWKOWO', 'T.G. SOKÓŁ GNIEWKOWO'),
    ('team', 'GWIAZDY NESTLÉ FITNESS', 'GWIAZDY NESTLE FITNESS'),
    
    # ('team', 'ZAKOLATEAM', '#ZAKOLATEAM'),
    # ('team', 'PARKRUN', 'PARKRUN TORUŃ'),
    # ('team', 'T.G.SOKÓŁ', 'TG SOKÓŁ GNIEWKOWO'),
    # ('team', 'T.G..SOKÓŁ GNIEWKOWO', 'TG SOKÓŁ GNIEWKOWO'),
    # ('city', 'TORUN', 'TORUŃ'),
]
for field, from_, to_ in fixes:
    torun.loc[torun[field] == from_, field] = to_
    
torun

,name,city,team,gender,category,result_torun,year_of_birth
0,RYNKOWSKI BARTOSZ,IŁAWA,None,M,M30-39,00:31:39,NaN
1,TOMASZEWSKI MACIEJ,TORUŃ,GKS FABIANKI,M,M30-39,00:32:41,NaN
2,RATAJCZYK PRZEMYSŁAW,ALEKSANDRÓW KUJAWSKI,TKKF KOLEJARZ BYDGOSZCZ,M,M30-39,00:33:15,NaN
3,SANKO ALIAKSANDR,GRUDZIĄDZ,None,M,M30-39,00:33:33,NaN
4,PIASECKI KRZYSZOF,WŁOCŁAWEK,KUNA TEAM WŁOCŁAWEK,M,M30-39,00:33:54,NaN
...,...,...,...,...,...,...,...
504,OLSZOWY NIKODEM,TORUŃ,None,M,M20-29,01:13:49,NaN
505,ŁAPIŃSKI SZYMON,TORUŃ,KLEJONT NOLU,M,M40-49,01:15:11,NaN
506,LIWIŃSKI SŁAWOMIR,SĘKOCIN-LAS,None,M,M50-59,01:16:55,NaN
507,KUŁAKOWSKI ROBERT,TORUŃ,HENDRICKSON POLAND,M,M50-59,01:17:31,NaN
508,ADAMCZYK ZBIGNIEW,ZAMEK BIERZGŁOWSKI,ZABIEGANI ŁUBIANKA,M,M70,01:18:02,NaN

In [3]:
final = torun

# Adjust teams

In [4]:
final.loc[final['name'] == 'CIESIELSKI MACIEJ', 'team'] = 'PARKRUN TORUŃ - niezgłoszony'
final.loc[final['name'] == 'BARCZ ANNA', 'team'] = 'PARKRUN TORUŃ - niezgłoszony'
final.loc[final['name'] == 'BARCZ MACIEJ', 'team'] = 'PARKRUN TORUŃ - niezgłoszony'
final.loc[final['name'] == 'KRUCZKOWSKI JAROSŁAW', 'team'] = 'PARKRUN TORUŃ - niezgłoszony'
final.loc[final['name'] == 'SZARWIŃSKI MARIUSZ', 'team'] = 'PARKRUN TORUŃ'




# final.loc[final['name'] == 'TOMASZEWSKI WOJCIECH', 'team'] = 'TASMAN TEAM'
# final.loc[final['name'] == 'BONIECKA TERESA', 'team'] = 'RKS LECH RYPIN - niezgłoszona'
# final.loc[final['name'] == 'DANIELEWICZ DARIA', 'team'] = 'TG SOKÓŁ GNIEWKOWO - niezgłoszona'
final[final['team'] == 'PARKRUN TORUŃ']

,name,city,team,gender,category,result_torun,year_of_birth
29,WOJCIECHOWSKI PRZEMYSŁAW,TORUŃ,PARKRUN TORUŃ,M,M40-49,00:39:30,NaN
33,STRZELECKI MARIUSZ,BRZOZÓWKA,PARKRUN TORUŃ,M,M30-39,00:39:47,NaN
38,ROK-SZPALA SYLWIA,LUBICZ GÓRNY,PARKRUN TORUŃ,K,K40-49,00:40:46,NaN
42,JABŁOŃSKI DOMINIK,TORUŃ,PARKRUN TORUŃ,M,M40-49,00:41:07,NaN
50,MIEDZAK KAROL,TORUŃ,PARKRUN TORUŃ,M,M30-39,00:42:06,NaN
54,GOŁĘBIEWSKI MICHAŁ,TORUŃ,PARKRUN TORUŃ,M,M40-49,00:42:15,NaN
60,HUSSEIN ABDALLA,KONRADOWO,PARKRUN TORUŃ,M,M30-39,00:42:23,NaN
63,FRĄK EDYTA,TORUŃ,PARKRUN TORUŃ,K,K30-39,00:42:36,NaN
67,SŁUNIECKI TOMASZ,TORUŃ,PARKRUN TORUŃ,M,M50-59,00:42:45,NaN
69,DĘBICKI MACIEJ,GOSTKOWO,PARKRUN TORUŃ,M,M30-39,00:42:52,NaN
70,PAZDERSKA MAŁGORZATA,TORUŃ,PARKRUN TORUŃ,K,K40-49,00:42:57,NaN
74,SZARWIŃSKI MARIUSZ,TORUŃ,PARKRUN TORUŃ,M,M30-39,00:43:19,NaN
75,WIŚNIEWSKI JAKUB,SILNO,PARKRUN TORUŃ,M,M30-39,00:43:19,NaN
81,WYSOCKI DARIUSZ,TORUŃ,PARKRUN TORUŃ,M,M40-49,00:43:53,NaN
94,MIEDZAK DAWID,TORUŃ,PARKRUN TORUŃ,M,M30-39,00:44:43,NaN
96,OLSZEWSKI KAROL,TORUŃ,PARKRUN TORUŃ,M,M40-49,00:44:53,NaN
113,SZYMAŃSKI JAROSŁAW,TORUŃ,PARKRUN TORUŃ,M,M40-49,00:45:32,NaN
137,KOZICKI ROMAN,TORUŃ,PARKRUN TORUŃ,M,M50-59,00:46:38,NaN
145,GODLEWSKI KRZYSZTOF,TORUŃ,PARKRUN TORUŃ,M,M40-49,00:47:11,NaN
170,DUDKOWIAK MICHAŁ,TORUŃ,PARKRUN TORUŃ,M,M40-49,00:47:46,NaN
184,MĄCZKA ZBIGNIEW,TORUŃ,PARKRUN TORUŃ,M,M60-69,00:48:11,NaN
190,HUSSEIN ANNA,KONRADOWO,PARKRUN TORUŃ,K,K40-49,00:48:29,NaN
193,LUBISZEWSKI ROBERT,TORUŃ,PARKRUN TORUŃ,M,M30-39,00:48:31,NaN
225,KALINOWSKI ARKADIUSZ,TORUŃ,PARKRUN TORUŃ,M,M40-49,00:49:29,NaN
230,SŁUNIECKA ALEKSANDRA,TORUŃ,PARKRUN TORUŃ,K,K20-29,00:49:41,NaN
247,BAJEŃSKI DARIUSZ,TORUŃ,PARKRUN TORUŃ,M,M30-39,00:50:12,NaN
255,CIESIELSKI JAN,TORUŃ,PARKRUN TORUŃ,M,M50-59,00:50:32,NaN
258,KACZOROWSKA ANNA,TORUŃ,PARKRUN TORUŃ,K,K40-49,00:50:40,NaN
263,JANISZEWSKI DARIUSZ,TORUŃ,PARKRUN TORUŃ,M,M50-59,00:51:03,NaN
275,ŻYŁKOWSKA KRYSTYNA,TORUN,PARKRUN TORUŃ,K,K60-69,00:51:36,NaN
280,WALKOWIAK KRZYSZTOF,TORUŃ,PARKRUN TORUŃ,M,M30-39,00:51:56,NaN
284,FRĄCZYK JAROSŁAW,TORUŃ,PARKRUN TORUŃ,M,M50-59,00:52:02,NaN
305,WIŚNIEWSKA DANIELA,LUBICZ GÓRNY,PARKRUN TORUŃ,K,K40-49,00:53:07,NaN
306,JAWORSKI JAROSŁAW,TORUŃ,PARKRUN TORUŃ,M,M50-59,00:53:08,NaN
311,KUDŁA AGNIESZKA,TORUŃ,PARKRUN TORUŃ,K,K40-49,00:53:33,NaN
326,FRĄCZYK ANNA,TORUŃ,PARKRUN TORUŃ,K,K40-49,00:54:18,NaN
329,WASIECZKO MATEUSZ,KOPANINO,PARKRUN TORUŃ,M,M40-49,00:54:20,NaN
410,WOJCIECHOWSKI SŁAWOMIR,LUBICZ DOLNY,PARKRUN TORUŃ,M,M40-49,00:58:33,NaN
462,SYROCKA AGNIESZKA,TORUŃ,PARKRUN TORUŃ,K,K40-49,01:04:19,NaN

In [5]:
# sorted(final[final['team'].notnull()]['team'].unique())

## Save

In [6]:
def to_seconds(time_str):
    t = datetime.time.fromisoformat(time_str)
    return t.hour * 3600 + t.minute * 60 + t.second

def to_time_str(seconds):
    return datetime.datetime.fromtimestamp(seconds, datetime.UTC).strftime('%T')

def gp_round(n):
    if n - math.floor(n) < 0.5:
        return math.floor(n)
    return math.ceil(n)

def get_result(row):
    results = [(col[len('result_'):], row[col]) for col in row.index if col.startswith('result_') and type(row[col]) == str]
    row['total_runs'] = len(results)
    best_6_runs = sorted([(r[0], to_seconds(r[1])) for r in results], key=lambda r: r[1])[:6]
    row['avg_result'] = gp_round(sum([r[1] for r in best_6_runs]) / len(best_6_runs))
    row['best_runs'] = ','.join(r[0] for r in best_6_runs)
    row['avg_result_str'] = to_time_str(row['avg_result'])
    return row

In [7]:
def get_category(row):
    if pd.isnull(row['year_of_birth']):
        return row

    if row['year_of_birth'] > year - 30:
        row['category'] = row['gender'] + '18'
    elif row['year_of_birth'] > year - 40:
        row['category'] = row['gender'] + '30'
    elif row['year_of_birth'] > year - 50:
        row['category'] = row['gender'] + '40'
    elif row['year_of_birth'] > year - 60:
        row['category'] = row['gender'] + '50'
    elif row['year_of_birth'] > year - 65:
        row['category'] = row['gender'] + '60'
    elif row['year_of_birth'] > year - 70:
        row['category'] = row['gender'] + '65'
    elif row['year_of_birth'] > year - 75:
        row['category'] = row['gender'] + '70'
    elif row['year_of_birth'] > year - 80:
        row['category'] = row['gender'] + '75'
    elif row['year_of_birth'] > year - 86:
        row['category'] = row['gender'] + '80'
    else:
        row['category'] = row['gender'] + '85'

    return row
        
gp = final.apply(get_result, axis=1)
gp['year_of_birth'] = gp['year_of_birth'].astype('Int64')
gp = gp.apply(get_category, axis=1)
gp

,name,city,team,gender,category,result_torun,year_of_birth,total_runs,avg_result,best_runs,avg_result_str
0,RYNKOWSKI BARTOSZ,IŁAWA,None,M,M30-39,00:31:39,<NA>,1,1899,torun,00:31:39
1,TOMASZEWSKI MACIEJ,TORUŃ,GKS FABIANKI,M,M30-39,00:32:41,<NA>,1,1961,torun,00:32:41
2,RATAJCZYK PRZEMYSŁAW,ALEKSANDRÓW KUJAWSKI,TKKF KOLEJARZ BYDGOSZCZ,M,M30-39,00:33:15,<NA>,1,1995,torun,00:33:15
3,SANKO ALIAKSANDR,GRUDZIĄDZ,None,M,M30-39,00:33:33,<NA>,1,2013,torun,00:33:33
4,PIASECKI KRZYSZOF,WŁOCŁAWEK,KUNA TEAM WŁOCŁAWEK,M,M30-39,00:33:54,<NA>,1,2034,torun,00:33:54
...,...,...,...,...,...,...,...,...,...,...,...
504,OLSZOWY NIKODEM,TORUŃ,None,M,M20-29,01:13:49,<NA>,1,4429,torun,01:13:49
505,ŁAPIŃSKI SZYMON,TORUŃ,KLEJONT NOLU,M,M40-49,01:15:11,<NA>,1,4511,torun,01:15:11
506,LIWIŃSKI SŁAWOMIR,SĘKOCIN-LAS,None,M,M50-59,01:16:55,<NA>,1,4615,torun,01:16:55
507,KUŁAKOWSKI ROBERT,TORUŃ,HENDRICKSON POLAND,M,M50-59,01:17:31,<NA>,1,4651,torun,01:17:31
508,ADAMCZYK ZBIGNIEW,ZAMEK BIERZGŁOWSKI,ZABIEGANI ŁUBIANKA,M,M70,01:18:02,<NA>,1,4682,torun,01:18:02

In [8]:
gp.to_sql(name='results', con=cnx, if_exists='replace', index_label='id')

509