In [1]:
import pandas as pd
import numpy as np
import json
import math
import sqlite3
import datetime
import html_to_json
year = 2026
pd.set_option('display.max_columns', None)
cnx = sqlite3.connect('results.db')

def diff(df, column, suffixes):
    c1 = column + suffixes[0]
    c2 = column + suffixes[1]
    return df[df[c1].notnull() & df[c2].notnull() & (df[c1] != df[c2])]

# Toruń

```
curl 'https://live.sts-timing.pl/TrylogiaTorunskichLegend/I/api.php?action=load-more-results&i=0&d=2&p=false&filtr=false' >> torun.json 
echo >> torun.json 
curl 'https://live.sts-timing.pl/TrylogiaTorunskichLegend/I/api.php?action=load-more-results&i=500&d=2&p=false&filtr=false' >> torun.json 
echo >> torun.json 
```

In [2]:
html = '<table>'
with open('torun.json') as f:
    for line in f.readlines():
        html += json.loads(line)['html']

html += '</table>'
table = html_to_json.convert_tables(html)[0]
torun = pd.DataFrame(table, columns=[
    'place',
    'bib',
    'name',
    'city',
    'team',
    'gender',
    '_c0',
    'category',
    '_c1',
    'gun_time',
    'result_torun',
    '_c2',
])
torun = torun[['name', 'city', 'team', 'gender', 'category', 'result_torun']]
torun['name'] = torun['name'].str.upper()
torun['city'] = torun['city'].str.upper()
torun['category'] = torun['category'].str.slice(0, 3)
torun['team'] = torun['team'].str.upper().replace('', None)

fixes = [
    ('name', 'KUDLA AGNIESZKA', 'KUDŁA AGNIESZKA'),
    ('team', 'ECIT NORIAN / PARKRUN TORUŃ', 'PARKRUN TORUŃ'),
    ('name', 'SZARWIŃSKI SZARWIŃSKI', 'SZARWIŃSKI MARIUSZ'),
    ('team', 'AKTYWNY  GRUDZIĄDZ', 'AKTYWNY GRUDZIĄDZ'),
    ('team', 'BIEGOWI PRZYJACIELE.', 'BIEGOWI PRZYJACIELE'),
    ('team', 'T.G.SOKÓŁ GNIEWKOWO', 'T.G. SOKÓŁ GNIEWKOWO'),
    ('team', 'TG SOKÓŁ GNIEWKOWO', 'T.G. SOKÓŁ GNIEWKOWO'),
    ('team', 'GWIAZDY NESTLÉ FITNESS', 'GWIAZDY NESTLE FITNESS'),
    ('team', 'SOKÓŁ GNIEWKOWO', 'T.G. SOKÓŁ GNIEWKOWO'),
    ('name', 'JABLONSKI JAROSLAW', 'JABŁOŃSKI JAROSŁAW'),
    ('name', 'LOPATA SZYMON', 'ŁOPATA SZYMON'),
    ('name', 'CZAJKOWSKI ALEKSANDRA', 'CZAJKOWSKA ALEKSANDRA'),
    ('name', 'ZIELIŃSKI MACIEJ ZIELIŃSKI', 'ZIELIŃSKI MACIEJ'),
    ('name', 'PIASECKI KRZYSZOF', 'PIASECKI KRZYSZTOF'),
    ('name', 'TOMASZEWSKI MILOSZ', 'TOMASZEWSKI MIŁOSZ'),
    ('team', 'GKS FABIANKI RUN TORUŃ', 'GKS FABIANKI'),
    ('name', 'KRIGER ANNA', 'KRIGER-PRZYBYLSKA ANNA'),
    ('name', 'KRUSZYNA ROBER', 'KRUSZYNA ROBERT')
]
for field, from_, to_ in fixes:
    torun.loc[torun[field] == from_, field] = to_
    
torun

,name,city,team,gender,category,result_torun
0,RYNKOWSKI BARTOSZ,IŁAWA,None,M,M30,00:31:39
1,TOMASZEWSKI MACIEJ,TORUŃ,GKS FABIANKI,M,M30,00:32:41
2,RATAJCZYK PRZEMYSŁAW,ALEKSANDRÓW KUJAWSKI,TKKF KOLEJARZ BYDGOSZCZ,M,M30,00:33:15
3,SANKO ALIAKSANDR,GRUDZIĄDZ,None,M,M30,00:33:33
4,PIASECKI KRZYSZTOF,WŁOCŁAWEK,KUNA TEAM WŁOCŁAWEK,M,M30,00:33:54
...,...,...,...,...,...,...
504,OLSZOWY NIKODEM,TORUŃ,None,M,M20,01:13:49
505,ŁAPIŃSKI SZYMON,TORUŃ,KLEJONT NOLU,M,M40,01:15:11
506,LIWIŃSKI SŁAWOMIR,SĘKOCIN-LAS,None,M,M50,01:16:55
507,KUŁAKOWSKI ROBERT,TORUŃ,HENDRICKSON POLAND,M,M50,01:17:31
508,ADAMCZYK ZBIGNIEW,ZAMEK BIERZGŁOWSKI,ZABIEGANI ŁUBIANKA,M,M70,01:18:02

# Grudziądz

In [3]:
# curl https://wyniki.domtel-sport.pl/zawody/5-bronek-run-forest-edition/ | grep ptc_vars > grudziadz.js
with open('grudziadz.js') as f:
    raw_data = json.loads(f.read()[15:-2])['init_data']

data = [
    [
        r['Zawodnik'],
        r['Team'],
        r['Płeć'],
        r['Kat'],
        r['Czas netto'],
        r['Rocz']
    ]
    for r in raw_data
    if r['DYSTANS'] == '10:59-10 km' and r['Msc']
]
grudziadz = pd.DataFrame(data, columns=['name', 'team', 'gender', 'category', 'result_grudziadz', 'year_of_birth'])
grudziadz['name'] = grudziadz['name'].str.upper()
grudziadz['team'] = grudziadz['team'].str.upper().replace('', None)
grudziadz

,name,team,gender,category,result_grudziadz,year_of_birth
0,DIDOVODIUK DMYTRO,None,M,M30,00:31:53,1987
1,WAŚKIEWICZ SEBASTIAN,KB BIEGAJĄCY DIETETYK TEAM,M,M30,00:34:05,1987
2,TOMASZEWSKI MACIEJ,GKS FABIANKI,M,M30,00:35:01,1988
3,JANKOWIAK DAREK,SAMISWOI,M,M30,00:35:36,1995
4,PETROW DANIEL,GRUDZIĄDZ,M,M40,00:36:41,1986
...,...,...,...,...,...,...
151,GRZESZAK DANUTA,None,K,K70,01:11:32,1953
152,LEWANDOWSKI WOJCIECH,None,M,M70,01:14:37,1952
153,BRAC-WALCZYK MAŁGORZATA,None,K,K65,01:16:56,1958
154,BŁASZCZAK STANISŁAW,WKB MARATOŃCZYK WŁOCŁAWEK,M,M80,01:19:28,1946
155,GERKA KRZYSZTOF,RKS LECH RYPIN,M,M65,01:22:03,1957

In [4]:
after_2 = torun.merge(grudziadz, on=['name', 'gender'], how='outer', suffixes=('_torun', '_grudziadz'))

In [5]:
diff(after_2, 'category', ('_torun', '_grudziadz')) # looks OK!

,name,city,team_torun,gender,category_torun,result_torun,team_grudziadz,category_grudziadz,result_grudziadz,year_of_birth
72,CZAJKOWSKA ALEKSANDRA,BYDGOSZCZ,None,K,K20,01:02:04,None,K16,00:59:37,1997
83,DANIELEWICZ DARIA,GNIEWKOWO,T.G. SOKÓŁ GNIEWKOWO,K,K20,00:48:31,T.G. SOKÓŁ GNIEWKOWO,K16,00:47:53,1998
110,DŁONIAK EDMUND,GNIEWKOWO,T.G. SOKÓŁ GNIEWKOWO,M,M70,01:06:27,T.G. SOKÓŁ GNIEWKOWO,M80,01:06:05,1945
124,GABIZDALSKA ALICJA,OSTROWO,T.G. SOKÓŁ GNIEWKOWO,K,K20,00:57:36,T.G. SOKÓŁ GNIEWKOWO,K16,00:58:10,1999
354,MĄCZKA ZBIGNIEW,TORUŃ,PARKRUN TORUŃ,M,M60,00:48:11,PARKRUN TORUŃ,M65,00:47:38,1957
407,PIONTEK ELŻBIETA,BYDGOSZCZ,None,K,K60,01:01:58,None,K65,01:06:59,1957
464,SOWIŃSKI EDMUND,PŁOCK,TKKF PŁOCK,M,M70,01:03:06,TKKF PŁOCK,M80,01:04:06,1942
604,ŻYŁKOWSKA KRYSTYNA,TORUN,PARKRUN TORUŃ,K,K60,00:51:36,PARKRUN TORUŃ,K65,00:54:53,1960

In [6]:
diff(after_2, 'team', ('_torun', '_grudziadz')) # looks OK!

,name,city,team_torun,gender,category_torun,result_torun,team_grudziadz,category_grudziadz,result_grudziadz,year_of_birth
570,WĄŻ SŁAWOMIR,GRĘBOCIN,GWIAZDY NESTLE FITNESS,M,M50,01:03:50,RCR,M50,01:01:34,1972
593,ŁOPATA SZYMON,PAPOWO TORUNSKIE,BIEGOWI PRZYJACIELE,M,M40,00:41:04,PAPOWO TORUŃSKIE,M40,00:42:57,1986

In [7]:
after_2['team'] = after_2['team_grudziadz'].combine_first(after_2['team_torun'])
after_2['category'] = after_2['category_grudziadz'].combine_first(after_2['category_torun'])
after_2 = after_2.drop(labels=['team_grudziadz', 'team_torun', 'category_grudziadz', 'category_torun'], axis=1)
after_2

,name,city,gender,result_torun,result_grudziadz,year_of_birth,team,category
0,ADAMCZYK ZBIGNIEW,ZAMEK BIERZGŁOWSKI,M,01:18:02,NaN,NaN,ZABIEGANI ŁUBIANKA,M70
1,AFTYKA TOMASZ,GRUDZIĄDZ,M,00:50:03,NaN,NaN,RTR,M50
2,AGUADO OREGUI LIDIA,TORUŃ,K,00:49:55,NaN,NaN,None,K20
3,ANDRZEJCZAK MACIEJ,ŁĘCZYCA,M,00:42:21,NaN,NaN,ZESPÓŁ SZKÓŁ IM. JADWIGI GRODZKIEJ,M16
4,ANTONOWICZ WOJCIECH,SZCZECIN,M,00:45:07,NaN,NaN,None,M60
...,...,...,...,...,...,...,...,...
601,ŻUCHOWSKA PAULINA,NaN,K,NaN,00:49:49,1996,AZS UMK TORUŃ,K30
602,ŻUCHOWSKI RADOSŁAW,TORUŃ,M,00:55:10,NaN,NaN,None,M30
603,ŻYŁA JUSTYNA,NaN,K,NaN,00:50:27,1977,LA RIVE SPORT TEAM,K40
604,ŻYŁKOWSKA KRYSTYNA,TORUN,K,00:51:36,00:54:53,1960,PARKRUN TORUŃ,K65
605,ŻÓRAWSKA BARBARA,WARSZAWA,K,01:03:45,NaN,NaN,None,K20

# Fabianki

In [8]:
# curl https://wyniki.domtel-sport.pl/zawody/fabianki-na-dyche/ | grep ptc_vars > fabianki.js
with open('fabianki.js') as f:
    raw_data = json.loads(f.read()[15:-2])['init_data']

data = [
    [
        r['Zawodnik'],
        r['Team'],
        r['Płeć'],
        r['Kat'],
        r['Czas netto'],
        r['Rocz']
    ]
    for r in raw_data
    if r['Msc'] and r['Zawodnik'] not in ('WOJCIECHOWSKI Sławomir')
]
fabianki = pd.DataFrame(data, columns=['name', 'team', 'gender', 'category', 'result_fabianki', 'year_of_birth'])
fabianki['name'] = fabianki['name'].str.upper()
fabianki['team'] = fabianki['team'].str.upper().replace('', None)

fixes = [
    ('team', 'PARKUN TORUŃ', 'PARKRUN TORUŃ'),
    ('team', 'KUNA TEAM', 'KUNA TEAM WŁOCŁAWEK'),
    ('name', 'ROGOZINSKI DAWID', 'ROGOZIŃSKI DAWID')
]
for field, from_, to_ in fixes:
    fabianki.loc[fabianki[field] == from_, field] = to_

fabianki

,name,team,gender,category,result_fabianki,year_of_birth
0,TOMASZEWSKI MACIEJ,GKS FABIANKI,M,M30,00:33:04,1988
1,RATAJCZYK PRZEMYSŁAW,TKKF KOLEJARZ BYDGOSZCZ,M,M30,00:33:40,1993
2,JARANOWSKI ANDRZEJ,GKS FABIANKI,M,M30,00:33:57,1993
3,ROGOZIŃSKI DAWID,TEAMOCHAL,M,M30,00:34:44,1988
4,PIASECKI KRZYSZTOF,KUNA TEAM WŁOCŁAWEK,M,M30,00:34:52,1988
...,...,...,...,...,...,...
164,WLAZLO-WNUKIEWICZ ANNA,KROJCZYN,K,K40,01:13:28,1983
165,GLAZIK RENATA,FABIANKI,K,K50,01:13:31,1975
166,GERKA KRZYSZTOF,RKS LECH RYPIN,M,M60,01:14:02,1957
167,BŁASZCZAK STANISŁAW,WKB MARATOŃCZYK WŁOCŁAWEK,M,M80+,01:14:40,1946
168,MĄCZKA MAŁGORZATA,PARKRUN TORUŃ,K,K60,01:17:39,1961

In [9]:
after_3 = after_2.merge(fabianki, on=['name', 'gender'], how='outer', suffixes=('_base', '_fabianki'))

In [10]:
diff(after_3, 'category', ('_base', '_fabianki')) # looks OK!

,name,city,gender,result_torun,result_grudziadz,year_of_birth_base,team_base,category_base,team_fabianki,category_fabianki,result_fabianki,year_of_birth_fabianki
20,BEREBECKI ROMAN,NaN,M,NaN,00:50:29,1951,RKS LECH RYPIN,M75,RKS LECH RYPIN,M70,00:49:01,1951
54,BŁASZCZAK STANISŁAW,NaN,M,NaN,01:19:28,1946,WKB MARATOŃCZYK WŁOCŁAWEK,M80,WKB MARATOŃCZYK WŁOCŁAWEK,M80+,01:14:40,1946
124,DŁONIAK EDMUND,GNIEWKOWO,M,01:06:27,01:06:05,1945,T.G. SOKÓŁ GNIEWKOWO,M80,T.G. SOKÓŁ GNIEWKOWO,M80+,01:03:58,1945
146,GERKA KRZYSZTOF,NaN,M,NaN,01:22:03,1957,RKS LECH RYPIN,M65,RKS LECH RYPIN,M60,01:14:02,1957
176,GRZESZAK DANUTA,MOGILNO,K,01:07:28,01:11:32,1953,None,K70,MOGILNO,K70+,01:06:21,1953
354,MACIEJA BARTOSZ,SZPETAL GÓRNY,M,00:39:25,NaN,NaN,KUNA TEAM WŁOCŁAWEK,M20,KUNA TEAM WŁOCŁAWEK,M16,00:38:29,2006
394,MĄCZKA ZBIGNIEW,TORUŃ,M,00:48:11,00:47:38,1957,PARKRUN TORUŃ,M65,PARKRUN TORUŃ,M60,00:46:59,1957
421,OSTROWSKI SZYMON,WŁOCŁAWEK,M,00:41:26,NaN,NaN,None,M20,WŁOCŁAWEK,M16,00:41:07,1997
448,PIETRZAK MICHAŁ,WŁOCŁAWK,M,00:35:51,NaN,NaN,KUNA TEAM WŁOCŁAWEK,M20,KUNA TEAM WŁOCŁAWEK,M16,00:36:42,2005
454,PIOTROWICZ IRENEUSZ,NaN,M,NaN,00:55:41,1960,NaN,M65,PIOTRKÓW KUJAWSKI,M60,00:52:08,1960
563,SŁUNIECKA ALEKSANDRA,TORUŃ,K,00:49:41,NaN,NaN,PARKRUN TORUŃ,K20,PARKRUN TORUŃ,K16,00:51:07,2002
617,WIŚNIEWSKI DAMIAN,,M,00:43:44,NaN,NaN,None,,KUJAWSKO-POMORSKIE,M30,00:42:54,1987
620,WIŚNIEWSKI KAROL,TORUŃ,M,00:58:00,NaN,NaN,None,M20,PŁOCK,M16,00:54:52,1998
678,ŻYŁKOWSKA KRYSTYNA,TORUN,K,00:51:36,00:54:53,1960,PARKRUN TORUŃ,K65,PARKRUN TORUŃ,K60,00:51:38,1960

In [11]:
diff(after_3, 'year_of_birth', ('_base', '_fabianki')) # looks OK!

Empty DataFrame
Columns: [name, city, gender, result_torun, result_grudziadz, year_of_birth_base, team_base, category_base, team_fabianki, category_fabianki, result_fabianki, year_of_birth_fabianki]
Index: []

In [12]:
diff(after_3, 'team', ('_base', '_fabianki')) # looks OK!

,name,city,gender,result_torun,result_grudziadz,year_of_birth_base,team_base,category_base,team_fabianki,category_fabianki,result_fabianki,year_of_birth_fabianki
305,KUBERSKI KRZYSZTOF,LIPNO,M,00:44:29,NaN,NaN,ARCZ*CIACH,M30,ARCZCIACH,M30,00:41:22,1989
637,WĄŻ SŁAWOMIR,GRĘBOCIN,M,01:03:50,01:01:34,1972,RCR,M50,GRĘBOCIN,M50,00:54:22,1972

In [13]:
after_3['team'] = after_3['team_base'].combine_first(after_3['team_fabianki'])
after_3['category'] = after_3['category_base'].combine_first(after_3['category_fabianki'])
after_3['year_of_birth'] = after_3['year_of_birth_base'].combine_first(after_3['year_of_birth_fabianki'])
after_3 = after_3.drop(labels=['team_base', 'team_fabianki', 'category_base', 'category_fabianki', 'year_of_birth_base', 'year_of_birth_fabianki'], axis=1)
after_3

,name,city,gender,result_torun,result_grudziadz,result_fabianki,team,category,year_of_birth
0,ADAMCZYK ZBIGNIEW,ZAMEK BIERZGŁOWSKI,M,01:18:02,NaN,NaN,ZABIEGANI ŁUBIANKA,M70,NaN
1,AFTYKA TOMASZ,GRUDZIĄDZ,M,00:50:03,NaN,NaN,RTR,M50,NaN
2,AGUADO OREGUI LIDIA,TORUŃ,K,00:49:55,NaN,NaN,NaN,K20,NaN
3,ANDRZEJCZAK MACIEJ,ŁĘCZYCA,M,00:42:21,NaN,NaN,ZESPÓŁ SZKÓŁ IM. JADWIGI GRODZKIEJ,M16,NaN
4,ANTONOWICZ WOJCIECH,SZCZECIN,M,00:45:07,NaN,NaN,NaN,M60,NaN
...,...,...,...,...,...,...,...,...,...
675,ŻUCHOWSKI JÓZEF,NaN,M,NaN,NaN,00:40:32,PŁONNE,M50,1971
676,ŻUCHOWSKI RADOSŁAW,TORUŃ,M,00:55:10,NaN,NaN,NaN,M30,NaN
677,ŻYŁA JUSTYNA,NaN,K,NaN,00:50:27,NaN,LA RIVE SPORT TEAM,K40,1977
678,ŻYŁKOWSKA KRYSTYNA,TORUN,K,00:51:36,00:54:53,00:51:38,PARKRUN TORUŃ,K65,1960
679,ŻÓRAWSKA BARBARA,WARSZAWA,K,01:03:45,NaN,NaN,NaN,K20,NaN

## Waganiec

```
curl 'https://live.sts-timing.pl/waganiec2026/api.php?action=load-more-results&i=0&d=1&p=false&filtr=false' >> waganiec.json
echo >> waganiec.json 
curl 'https://live.sts-timing.pl/waganiec2026/api.php?action=load-more-results&i=100&d=1&p=false&filtr=false' >> waganiec.json
echo >> waganiec.json 
```

In [14]:
html = '<table>'
with open('waganiec.json') as f:
    for line in f.readlines():
        html += json.loads(line)['html']

html += '</table>'
table = html_to_json.convert_tables(html)[0]
waganiec = pd.DataFrame(table, columns=[
    'place',
    'bib',
    'name',
    'country',
    'city',
    'team',
    'gender',
    '_c0',
    'category',
    '_c1',
    'gun_time',
    'result_waganiec',
    '_c2',
])
waganiec = waganiec[['name', 'city', 'team', 'gender', 'result_waganiec', 'category']]
waganiec['name'] = waganiec['name'].str.upper()
waganiec['city'] = waganiec['city'].str.upper()
waganiec['team'] = waganiec['team'].str.upper().replace('', None)
waganiec['result_waganiec'] = waganiec['result_waganiec'].str.zfill(8).replace('^000', '00:', regex=True)
waganiec['category'] = waganiec['category'] + '0'

fixes = [
    ('team', 'TG SOKÓŁ GNIEWKOWO', 'T.G. SOKÓŁ GNIEWKOWO'),
    ('team', 'PARKRUN TORUN', 'PARKRUN TORUŃ'),
    ('team', 'PARKTUN TORUŃ', 'PARKRUN TORUŃ'),
    ('team', 'PARKUN TORUŃ', 'PARKRUN TORUŃ'),
    ('team', 'PARKRUN  TORUŃ', 'PARKRUN TORUŃ'),
    ('team', 'PARKRUN NOWY PARK SOLANKOWY, INOWROCŁAW', 'PARKRUN NOWY PARK SOLANKOWY INOWROCŁAW'),
    ('team', 'KUNA TEAM WLOCLAWEK', 'KUNA TEAM WŁOCŁAWEK'),
    ('team', 'WATAHA ŁĄCZY NAS BIEGANIE', 'WATAHA - ŁĄCZY NAS BIEGANIE'),
    ('name', 'KRIGER PRZYBYLSKA ANNA', 'KRIGER-PRZYBYLSKA ANNA'),
]
for field, from_, to_ in fixes:
    waganiec.loc[waganiec[field] == from_, field] = to_

waganiec.loc[(waganiec['name'] == 'LEWANDOWSKI MACIEJ') & (waganiec['city'] == 'KONECK'), 'name'] = 'LEWANDOWSKI MACIEJ (KONECK)'
    
waganiec

,name,city,team,gender,result_waganiec,category
0,TOMASZEWSKI MACIEJ,TORUŃ,GKS FABIANKI,M,00:33:00,M30
1,RATAJCZYK PRZEMYSŁAW,ALEKSANDRÓW KUJAWSKI,TKKF KOLEJARZ BYDGOSZCZ,M,00:33:35,M30
2,TOMASZEWSKI MIŁOSZ,TORUŃ,GKS FABIANKI,M,00:33:38,M30
3,JARANOWSKI ANDRZEJ,BRODNICA,GKS FABIANKI,M,00:34:13,M30
4,JANKOWIAK DAREK,STRZELNO,SAMISWOI,M,00:34:49,M30
...,...,...,...,...,...,...
160,BOBER JOANNA,ALEKSANDRÓW KUJAWSKI,None,K,01:16:22,K30
161,BŁASZCZAK STANISŁAW,SKĘPE,WKB MARATOŃCZYK WŁOCŁAWEK,M,01:16:22,M70
162,ROSZAK MARZENA,GNIEWKOWO,None,K,01:25:23,K30
163,GERKA KRZYSZTOF,BRZUZE,RKS LECH RYPIN,M,01:26:41,M60
164,DOBROWOLSKI STANISŁAW,WAGANIEC,None,M,01:28:12,M70

In [15]:
after_4 = after_3.merge(waganiec, on=['name', 'gender'], how='outer', suffixes=('_base', '_waganiec'))

In [16]:
diff(after_4, 'team', ('_base', '_waganiec')) # looks OK!

Empty DataFrame
Columns: [name, city_base, gender, result_torun, result_grudziadz, result_fabianki, team_base, category_base, year_of_birth, city_waganiec, team_waganiec, result_waganiec, category_waganiec]
Index: []

In [17]:
diff(after_4, 'category', ('_base', '_waganiec')) # looks OK!

,name,city_base,gender,result_torun,result_grudziadz,result_fabianki,team_base,category_base,year_of_birth,city_waganiec,team_waganiec,result_waganiec,category_waganiec
21,BEREBECKI ROMAN,NaN,M,NaN,00:50:29,00:49:01,RKS LECH RYPIN,M75,1951,RYPIN,RKS LECH RYPIN,00:49:09,M70
58,BŁASZCZAK STANISŁAW,NaN,M,NaN,01:19:28,01:14:40,WKB MARATOŃCZYK WŁOCŁAWEK,M80,1946,SKĘPE,WKB MARATOŃCZYK WŁOCŁAWEK,01:16:22,M70
85,CZAJKOWSKA ALEKSANDRA,BYDGOSZCZ,K,01:02:04,00:59:37,00:55:35,BYDGOSZCZ,K16,1997,BYDGOSZCZ,None,00:58:55,K20
128,DZIEŁAK PATRYCJA,CZYSTOCHLEB,K,01:02:05,NaN,00:52:56,CZYSTOCHLEB,K16,2008,CZYSTOCHLEB,None,00:58:55,K10
133,DŁONIAK EDMUND,GNIEWKOWO,M,01:06:27,01:06:05,01:03:58,T.G. SOKÓŁ GNIEWKOWO,M80,1945,GNIEWKOWO,T.G. SOKÓŁ GNIEWKOWO,01:04:38,M70
141,FRĄCKOWIAK PAWEŁ,JANIKOWO,M,00:53:38,NaN,NaN,NaN,M16,NaN,JANIKOWO,None,00:55:45,M10
156,GERKA KRZYSZTOF,NaN,M,NaN,01:22:03,01:14:02,RKS LECH RYPIN,M65,1957,BRZUZE,RKS LECH RYPIN,01:26:41,M60
273,KIPRIJANOVSKI WIKTORIA,NaN,K,NaN,NaN,00:39:13,KUJAWSKO-POMORSKIE,K16,2001,TORUN,KUJAWSKO-POMORSKIE,00:38:51,K20
278,KLIMEK WIKTOR,NaN,M,NaN,NaN,00:47:26,KRUKOWO,M16,2007,CHOCEŃ,None,00:46:51,M10
423,MĄCZKA ZBIGNIEW,TORUŃ,M,00:48:11,00:47:38,00:46:59,PARKRUN TORUŃ,M65,1957,TORUŃ,PARKRUN TORUŃ,00:49:26,M60
479,PIEROWSKI ARKADIUSZ,NaN,M,NaN,NaN,00:53:57,ŁĘG WITOSZYN,M16,1997,ŁĘG WITOSZYN,None,00:53:05,M20
486,PIOTROWICZ IRENEUSZ,NaN,M,NaN,00:55:41,00:52:08,PIOTRKÓW KUJAWSKI,M65,1960,PIOTRKÓW KUJAWSKI,None,00:53:35,M60
563,SOWIŃSKI EDMUND,PŁOCK,M,01:03:06,01:04:06,NaN,TKKF PŁOCK,M80,1942,PŁOCK,TKKF PŁOCK,01:03:28,M70
667,WIŚNIEWSKI DAMIAN,,M,00:43:44,NaN,00:42:54,KUJAWSKO-POMORSKIE,,1987,TORUŃ,KUJAWSKO-POMORSKIE,00:44:02,M30

In [18]:
diff(after_4, 'city', ('_base', '_waganiec')) # looks OK!

,name,city_base,gender,result_torun,result_grudziadz,result_fabianki,team_base,category_base,year_of_birth,city_waganiec,team_waganiec,result_waganiec,category_waganiec
71,CHĘSIAK MATEUSZ,WAGANIEC,M,00:46:53,NaN,NaN,NaN,M30,NaN,WŁOSZYCA,None,00:47:25,M30
92,CZERENKIEWICZ-PAŁUCKA JOANNA,WŁOCŁAWEK,K,00:47:31,00:49:23,00:46:53,KUNA TEAM WŁOCŁAWEK,K50,1975,MACHNACZ,KUNA TEAM WŁOCŁAWEK,00:48:07,K50
149,GAC MONIKA,TORUŃ,K,00:49:23,00:51:39,00:48:31,T.G. SOKÓŁ GNIEWKOWO,K50,1976,GNIEWKOWO,T.G. SOKÓŁ GNIEWKOWO,00:49:11,K50
359,LEWANDOWSKI ARTUR,WŁOCŁAWEK,M,00:50:48,NaN,00:47:07,KUNA TEAM WŁOCŁAWEK,M50,1971,SZPETAL GÓRNY,KUNA TEAM WŁOCŁAWEK,00:47:22,M50
482,PIKULSKA JOANNA,LITYCHOWO,K,00:57:04,00:52:10,00:49:56,KS ZRYW RADZIEJÓW,K30,1988,BYTOŃ,KS ZRYW RADZIEJÓW,00:52:19,K30
534,RZĄD SZYMON,TORUŃ,M,00:38:30,NaN,NaN,GRIT RC TORUŃ,M20,NaN,TORUN,None,00:39:15,M20
667,WIŚNIEWSKI DAMIAN,,M,00:43:44,NaN,00:42:54,KUJAWSKO-POMORSKIE,,1987,TORUŃ,KUJAWSKO-POMORSKIE,00:44:02,M30
675,WOJCIECHOWSKI SŁAWOMIR,LUBICZ DOLNY,M,00:58:33,NaN,NaN,PARKRUN TORUŃ,M40,NaN,TORUŃ,PARKRUN TORUŃ,00:59:03,M40

In [19]:
after_4['team'] = after_4['team_base'].combine_first(after_4['team_waganiec'])
after_4['category'] = after_4['category_base'].combine_first(after_4['category_waganiec'])
after_4 = after_4.drop(labels=['team_base', 'team_waganiec', 'category_waganiec', 'category_base'], axis=1)
after_4

,name,city_base,gender,result_torun,result_grudziadz,result_fabianki,year_of_birth,city_waganiec,result_waganiec,team,category
0,ADAMCZYK ZBIGNIEW,ZAMEK BIERZGŁOWSKI,M,01:18:02,NaN,NaN,NaN,NaN,NaN,ZABIEGANI ŁUBIANKA,M70
1,AFTYKA TOMASZ,GRUDZIĄDZ,M,00:50:03,NaN,NaN,NaN,NaN,NaN,RTR,M50
2,AGUADO OREGUI LIDIA,TORUŃ,K,00:49:55,NaN,NaN,NaN,NaN,NaN,NaN,K20
3,ANDRZEJCZAK MACIEJ,ŁĘCZYCA,M,00:42:21,NaN,NaN,NaN,NaN,NaN,ZESPÓŁ SZKÓŁ IM. JADWIGI GRODZKIEJ,M16
4,ANTONOWICZ WOJCIECH,SZCZECIN,M,00:45:07,NaN,NaN,NaN,NaN,NaN,NaN,M60
...,...,...,...,...,...,...,...,...,...,...,...
729,ŻUCHOWSKI JÓZEF,NaN,M,NaN,NaN,00:40:32,1971,RADOMIN,00:41:43,PŁONNE,M50
730,ŻUCHOWSKI RADOSŁAW,TORUŃ,M,00:55:10,NaN,NaN,NaN,NaN,NaN,NaN,M30
731,ŻYŁA JUSTYNA,NaN,K,NaN,00:50:27,NaN,1977,NaN,NaN,LA RIVE SPORT TEAM,K40
732,ŻYŁKOWSKA KRYSTYNA,TORUN,K,00:51:36,00:54:53,00:51:38,1960,NaN,NaN,PARKRUN TORUŃ,K65
733,ŻÓRAWSKA BARBARA,WARSZAWA,K,01:03:45,NaN,NaN,NaN,NaN,NaN,NaN,K20

In [20]:
final = after_4

# Adjust teams

In [21]:
final.loc[final['name'] == 'CIESIELSKI MACIEJ', 'team'] = 'PARKRUN TORUŃ - niezgłoszony'
final.loc[final['name'] == 'BARCZ ANNA', 'team'] = 'PARKRUN TORUŃ - niezgłoszony'
final.loc[final['name'] == 'BARCZ MACIEJ', 'team'] = 'PARKRUN TORUŃ - niezgłoszony'
final.loc[final['name'] == 'KRUCZKOWSKI JAROSŁAW', 'team'] = 'PARKRUN TORUŃ - niezgłoszony'
final.loc[final['name'] == 'SZARWIŃSKI MARIUSZ', 'team'] = 'PARKRUN TORUŃ'
final.loc[final['name'] == 'RZĄD SZYMON', 'team'] = 'BIEGOWI PRZYJACIELE'
final.loc[final['name'] == 'ŁOPATA SZYMON', 'team'] = 'BIEGOWI PRZYJACIELE'
final.loc[final['name'] == 'BARTKOWSKI SŁAWOMIR', 'category'] = 'M50'

final[final['team'] == 'PARKRUN TORUŃ']

,name,city_base,gender,result_torun,result_grudziadz,result_fabianki,year_of_birth,city_waganiec,result_waganiec,team,category
6,BAJEŃSKI DARIUSZ,TORUŃ,M,00:50:12,NaN,NaN,NaN,NaN,NaN,PARKRUN TORUŃ,M30
75,CIESIELSKI JAN,TORUŃ,M,00:50:32,NaN,NaN,NaN,NaN,NaN,PARKRUN TORUŃ,M50
105,DEPERAS ALEKSANDER,NaN,M,NaN,NaN,00:38:33,1984,NaN,NaN,PARKRUN TORUŃ,M40
119,DUDKOWIAK MICHAŁ,TORUŃ,M,00:47:46,NaN,00:46:20,1984,NaN,NaN,PARKRUN TORUŃ,M40
132,DĘBICKI MACIEJ,GOSTKOWO,M,00:42:52,00:42:43,00:41:33,1993,GOSTKOWO,00:42:37,PARKRUN TORUŃ,M30
143,FRĄCZYK ANNA,TORUŃ,K,00:54:18,00:56:45,NaN,1980,NaN,NaN,PARKRUN TORUŃ,K40
144,FRĄCZYK JAROSŁAW,TORUŃ,M,00:52:02,00:49:01,NaN,1976,NaN,NaN,PARKRUN TORUŃ,M50
145,FRĄK EDYTA,TORUŃ,K,00:42:36,00:43:43,00:41:39,1988,NaN,NaN,PARKRUN TORUŃ,K30
166,GODLEWSKI KRZYSZTOF,TORUŃ,M,00:47:11,00:47:47,00:45:51,1977,TORUŃ,00:46:23,PARKRUN TORUŃ,M40
170,GOŁĘBIEWSKI MICHAŁ,TORUŃ,M,00:42:15,NaN,00:41:19,1983,NaN,NaN,PARKRUN TORUŃ,M40
209,HUSSEIN ABDALLA,KONRADOWO,M,00:42:23,00:43:09,00:41:52,1987,KONRADOWO,00:42:13,PARKRUN TORUŃ,M30
210,HUSSEIN ANNA,KONRADOWO,K,00:48:29,00:51:42,00:48:28,1981,KONRADOWO,00:49:38,PARKRUN TORUŃ,K40
216,JABŁOŃSKI DOMINIK,TORUŃ,M,00:41:07,00:42:12,00:40:26,1980,TORUŃ,00:41:57,PARKRUN TORUŃ,M40
222,JANECZKO KATARZYNA,NaN,K,NaN,00:57:22,NaN,1982,TORUŃ,00:53:18,PARKRUN TORUŃ,K40
225,JANISZEWSKI DARIUSZ,TORUŃ,M,00:51:03,00:53:59,NaN,1973,TORUŃ,00:51:01,PARKRUN TORUŃ,M50
237,JAWORSKI JAROSŁAW,TORUŃ,M,00:53:08,00:57:51,NaN,1971,TORUŃ,00:50:00,PARKRUN TORUŃ,M50
250,KACZOROWSKA ANNA,TORUŃ,K,00:50:40,NaN,NaN,NaN,NaN,NaN,PARKRUN TORUŃ,K40
254,KALINOWSKI ARKADIUSZ,TORUŃ,M,00:49:29,00:50:18,00:47:56,1981,TORUŃ,00:49:58,PARKRUN TORUŃ,M40
280,KOPERSKI SEBASTIAN,NaN,M,NaN,00:58:52,NaN,1978,CZERNIKOWO,00:53:19,PARKRUN TORUŃ,M40
297,KOZICKI ROMAN,TORUŃ,M,00:46:38,00:46:57,00:45:05,1967,TORUŃ,00:46:46,PARKRUN TORUŃ,M50
330,KUDŁA AGNIESZKA,TORUŃ,K,00:53:33,00:53:55,NaN,1979,NaN,NaN,PARKRUN TORUŃ,K40
375,LUBISZEWSKI ROBERT,TORUŃ,M,00:48:31,00:48:44,NaN,1990,NaN,NaN,PARKRUN TORUŃ,M30
398,MECHLIŃSKI BARTŁOMIEJ,NaN,M,NaN,00:38:47,00:37:42,1979,TORUŃ,00:38:08,PARKRUN TORUŃ,M40
403,MIEDZAK DAWID,TORUŃ,M,00:44:43,00:45:04,00:43:45,1991,TORUŃ,00:44:17,PARKRUN TORUŃ,M30
404,MIEDZAK KAROL,TORUŃ,M,00:42:06,NaN,00:43:41,1994,TORUŃ,00:47:11,PARKRUN TORUŃ,M30
408,MOLTZAN ŁUKASZ,NaN,M,NaN,NaN,00:45:44,1985,NaN,NaN,PARKRUN TORUŃ,M40
422,MĄCZKA MAŁGORZATA,NaN,K,NaN,NaN,01:17:39,1961,NaN,NaN,PARKRUN TORUŃ,K60
423,MĄCZKA ZBIGNIEW,TORUŃ,M,00:48:11,00:47:38,00:46:59,1957,TORUŃ,00:49:26,PARKRUN TORUŃ,M65
447,OLSZEWSKI KAROL,TORUŃ,M,00:44:53,NaN,NaN,NaN,NaN,NaN,PARKRUN TORUŃ,M40
468,PAZDERSKA MAŁGORZATA,TORUŃ,K,00:42:57,00:43:48,00:43:05,1985,TORUŃ,00:45:00,PARKRUN TORUŃ,K40
514,ROK-SZPALA SYLWIA,LUBICZ GÓRNY,K,00:40:46,NaN,00:40:26,1981,LUBICZ GÓRNY,00:41:38,PARKRUN TORUŃ,K40
556,SMOLEŃ AGNIESZKA,NaN,K,NaN,NaN,01:01:12,1985,TORUŃ,01:00:24,PARKRUN TORUŃ,K40
573,STAWARSKA ELŻBIETA,NaN,K,NaN,00:52:14,00:49:51,1977,TORUŃ,00:51:06,PARKRUN TORUŃ,K40
579,STRZELECKI MARIUSZ,BRZOZÓWKA,M,00:39:47,NaN,00:40:26,1987,BRZOZÓWKA,00:42:17,PARKRUN TORUŃ,M30
583,SYROCKA AGNIESZKA,TORUŃ,K,01:04:19,01:03:00,01:00:21,1979,NaN,NaN,PARKRUN TORUŃ,K40
587,SZARWIŃSKI MARIUSZ,TORUŃ,M,00:43:19,NaN,00:42:05,1987,NaN,NaN,PARKRUN TORUŃ,M30
604,SZYMAŃSKI JAROSŁAW,TORUŃ,M,00:45:32,00:47:21,NaN,1979,NaN,NaN,PARKRUN TORUŃ,M40
611,SŁUNIECKA ALEKSANDRA,TORUŃ,K,00:49:41,NaN,00:51:07,2002,TORUŃ,00:51:05,PARKRUN TORUŃ,K20
612,SŁUNIECKI TOMASZ,TORUŃ,M,00:42:45,NaN,00:41:39,1975,TORUŃ,00:43:43,PARKRUN TORUŃ,M50
638,WALKOWIAK KRZYSZTOF,TORUŃ,M,00:51:56,NaN,00:52:02,1990,NaN,NaN,PARKRUN TORUŃ,M30
644,WASIECZKO MATEUSZ,KOPANINO,M,00:54:20,00:55:55,NaN,1979,NaN,NaN,PARKRUN TORUŃ,M40
647,WAWRZYNOWICZ SYLWESTER,NaN,M,NaN,NaN,NaN,NaN,TORUŃ,00:41:39,PARKRUN TORUŃ,M40
665,WIŚNIEWSKA DANIELA,LUBICZ GÓRNY,K,00:53:07,NaN,00:52:36,1981,LUBICZ GÓRNY,00:53:37,PARKRUN TORUŃ,K40
669,WIŚNIEWSKI JAKUB,SILNO,M,00:43:19,NaN,NaN,NaN,SILNO,00:44:01,PARKRUN TORUŃ,M30
674,WOJCIECHOWSKI PRZEMYSŁAW,TORUŃ,M,00:39:30,00:40:12,00:39:30,1985,TORUŃ,00:40:23,PARKRUN TORUŃ,M40
675,WOJCIECHOWSKI SŁAWOMIR,LUBICZ DOLNY,M,00:58:33,NaN,NaN,NaN,TORUŃ,00:59:03,PARKRUN TORUŃ,M40
676,WOJEWODA TOMASZ,NaN,M,NaN,NaN,00:46:12,1983,TORUŃ,00:46:11,PARKRUN TORUŃ,M40
687,WYSOCKI DARIUSZ,TORUŃ,M,00:43:53,00:44:27,00:43:23,1986,TORUŃ,00:44:34,PARKRUN TORUŃ,M40
709,ZIÓŁKOWSKI GRZEGORZ,NaN,M,NaN,00:43:38,NaN,1985,TORUŃ,00:44:28,PARKRUN TORUŃ,M40
732,ŻYŁKOWSKA KRYSTYNA,TORUN,K,00:51:36,00:54:53,00:51:38,1960,NaN,NaN,PARKRUN TORUŃ,K65

In [22]:
# sorted(final[final['team'].notnull()]['team'].unique())

## Save

In [23]:
def to_seconds(time_str):
    t = datetime.time.fromisoformat(time_str)
    return t.hour * 3600 + t.minute * 60 + t.second

def to_time_str(seconds):
    return datetime.datetime.fromtimestamp(seconds, datetime.UTC).strftime('%T')

def gp_round(n):
    if n - math.floor(n) < 0.5:
        return math.floor(n)
    return math.ceil(n)

def get_result(row):
    results = [(col[len('result_'):], row[col]) for col in row.index if col.startswith('result_') and type(row[col]) == str]
    row['total_runs'] = len(results)
    best_6_runs = sorted([(r[0], to_seconds(r[1])) for r in results], key=lambda r: r[1])[:6]
    row['avg_result'] = gp_round(sum([r[1] for r in best_6_runs]) / len(best_6_runs))
    row['best_runs'] = ','.join(r[0] for r in best_6_runs)
    row['avg_result_str'] = to_time_str(row['avg_result'])
    return row

In [24]:
def get_category(row):
    if pd.isnull(row['year_of_birth']):
        return row

    if row['year_of_birth'] > year - 30:
        row['category'] = row['gender'] + '18'
    elif row['year_of_birth'] > year - 40:
        row['category'] = row['gender'] + '30'
    elif row['year_of_birth'] > year - 50:
        row['category'] = row['gender'] + '40'
    elif row['year_of_birth'] > year - 60:
        row['category'] = row['gender'] + '50'
    elif row['year_of_birth'] > year - 65:
        row['category'] = row['gender'] + '60'
    elif row['year_of_birth'] > year - 70:
        row['category'] = row['gender'] + '65'
    elif row['year_of_birth'] > year - 75:
        row['category'] = row['gender'] + '70'
    elif row['year_of_birth'] > year - 80:
        row['category'] = row['gender'] + '75'
    elif row['year_of_birth'] > year - 86:
        row['category'] = row['gender'] + '80'
    else:
        row['category'] = row['gender'] + '85'

    return row
        
gp = final.apply(get_result, axis=1)
gp['year_of_birth'] = gp['year_of_birth'].astype('Int64')
gp = gp.apply(get_category, axis=1)
gp

,name,city_base,gender,result_torun,result_grudziadz,result_fabianki,year_of_birth,city_waganiec,result_waganiec,team,category,total_runs,avg_result,best_runs,avg_result_str
0,ADAMCZYK ZBIGNIEW,ZAMEK BIERZGŁOWSKI,M,01:18:02,NaN,NaN,<NA>,NaN,NaN,ZABIEGANI ŁUBIANKA,M70,1,4682,torun,01:18:02
1,AFTYKA TOMASZ,GRUDZIĄDZ,M,00:50:03,NaN,NaN,<NA>,NaN,NaN,RTR,M50,1,3003,torun,00:50:03
2,AGUADO OREGUI LIDIA,TORUŃ,K,00:49:55,NaN,NaN,<NA>,NaN,NaN,NaN,K20,1,2995,torun,00:49:55
3,ANDRZEJCZAK MACIEJ,ŁĘCZYCA,M,00:42:21,NaN,NaN,<NA>,NaN,NaN,ZESPÓŁ SZKÓŁ IM. JADWIGI GRODZKIEJ,M16,1,2541,torun,00:42:21
4,ANTONOWICZ WOJCIECH,SZCZECIN,M,00:45:07,NaN,NaN,<NA>,NaN,NaN,NaN,M60,1,2707,torun,00:45:07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,ŻUCHOWSKI JÓZEF,NaN,M,NaN,NaN,00:40:32,1971,RADOMIN,00:41:43,PŁONNE,M50,2,2468,"fabianki,waganiec",00:41:08
730,ŻUCHOWSKI RADOSŁAW,TORUŃ,M,00:55:10,NaN,NaN,<NA>,NaN,NaN,NaN,M30,1,3310,torun,00:55:10
731,ŻYŁA JUSTYNA,NaN,K,NaN,00:50:27,NaN,1977,NaN,NaN,LA RIVE SPORT TEAM,K40,1,3027,grudziadz,00:50:27
732,ŻYŁKOWSKA KRYSTYNA,TORUN,K,00:51:36,00:54:53,00:51:38,1960,NaN,NaN,PARKRUN TORUŃ,K65,3,3162,"torun,fabianki,grudziadz",00:52:42
733,ŻÓRAWSKA BARBARA,WARSZAWA,K,01:03:45,NaN,NaN,<NA>,NaN,NaN,NaN,K20,1,3825,torun,01:03:45

In [25]:
gp.to_sql(name='results', con=cnx, if_exists='replace', index_label='id')

734